// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/automotechnologies/doitpay-go/client/authentication"
	"github.com/automotechnologies/doitpay-go/client/disbursement"
	"github.com/automotechnologies/doitpay-go/client/merchants"
	"github.com/automotechnologies/doitpay-go/client/payment"
	"github.com/automotechnologies/doitpay-go/client/public_simulate"
	"github.com/automotechnologies/doitpay-go/client/q_r_i_s"
	"github.com/automotechnologies/doitpay-go/client/virtual_account"
)

// Default doitpay HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.doitpay.co"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new doitpay HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Doitpay {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new doitpay HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Doitpay {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new doitpay client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Doitpay {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Doitpay)
	cli.Transport = transport
	cli.Authentication = authentication.New(transport, formats)
	cli.Disbursement = disbursement.New(transport, formats)
	cli.Merchants = merchants.New(transport, formats)
	cli.Payment = payment.New(transport, formats)
	cli.PublicSimulate = public_simulate.New(transport, formats)
	cli.Qris = q_r_i_s.New(transport, formats)
	cli.VirtualAccount = virtual_account.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Doitpay is a client for doitpay
type Doitpay struct {
	Authentication authentication.ClientService

	Disbursement disbursement.ClientService

	Merchants merchants.ClientService

	Payment payment.ClientService

	PublicSimulate public_simulate.ClientService

	Qris q_r_i_s.ClientService

	VirtualAccount virtual_account.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Doitpay) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Authentication.SetTransport(transport)
	c.Disbursement.SetTransport(transport)
	c.Merchants.SetTransport(transport)
	c.Payment.SetTransport(transport)
	c.PublicSimulate.SetTransport(transport)
	c.Qris.SetTransport(transport)
	c.VirtualAccount.SetTransport(transport)
}
