// Code generated by go-swagger; DO NOT EDIT.

package virtual_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/automotechnologies/doitpay-go/models"
)

// NewDeleteV1VirtualAccountParams creates a new DeleteV1VirtualAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteV1VirtualAccountParams() *DeleteV1VirtualAccountParams {
	return &DeleteV1VirtualAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteV1VirtualAccountParamsWithTimeout creates a new DeleteV1VirtualAccountParams object
// with the ability to set a timeout on a request.
func NewDeleteV1VirtualAccountParamsWithTimeout(timeout time.Duration) *DeleteV1VirtualAccountParams {
	return &DeleteV1VirtualAccountParams{
		timeout: timeout,
	}
}

// NewDeleteV1VirtualAccountParamsWithContext creates a new DeleteV1VirtualAccountParams object
// with the ability to set a context for a request.
func NewDeleteV1VirtualAccountParamsWithContext(ctx context.Context) *DeleteV1VirtualAccountParams {
	return &DeleteV1VirtualAccountParams{
		Context: ctx,
	}
}

// NewDeleteV1VirtualAccountParamsWithHTTPClient creates a new DeleteV1VirtualAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteV1VirtualAccountParamsWithHTTPClient(client *http.Client) *DeleteV1VirtualAccountParams {
	return &DeleteV1VirtualAccountParams{
		HTTPClient: client,
	}
}

/*
DeleteV1VirtualAccountParams contains all the parameters to send to the API endpoint

	for the delete v1 virtual account operation.

	Typically these are written to a http.Request.
*/
type DeleteV1VirtualAccountParams struct {

	/* XCLIENTKEY.

	   Client Key
	*/
	XCLIENTKEY string

	/* Body.

	   Virtual Account Request
	*/
	Body *models.DeleteVirtualAccountRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete v1 virtual account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteV1VirtualAccountParams) WithDefaults() *DeleteV1VirtualAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete v1 virtual account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteV1VirtualAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) WithTimeout(timeout time.Duration) *DeleteV1VirtualAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) WithContext(ctx context.Context) *DeleteV1VirtualAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) WithHTTPClient(client *http.Client) *DeleteV1VirtualAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCLIENTKEY adds the xCLIENTKEY to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) WithXCLIENTKEY(xCLIENTKEY string) *DeleteV1VirtualAccountParams {
	o.SetXCLIENTKEY(xCLIENTKEY)
	return o
}

// SetXCLIENTKEY adds the xCLIENTKEY to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) SetXCLIENTKEY(xCLIENTKEY string) {
	o.XCLIENTKEY = xCLIENTKEY
}

// WithBody adds the body to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) WithBody(body *models.DeleteVirtualAccountRequest) *DeleteV1VirtualAccountParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) SetBody(body *models.DeleteVirtualAccountRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteV1VirtualAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-CLIENT-KEY
	if err := r.SetHeaderParam("X-CLIENT-KEY", o.XCLIENTKEY); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
