// Code generated by go-swagger; DO NOT EDIT.

package virtual_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/automotechnologies/doitpay-go/models"
)

// NewDeleteV1VirtualAccountParams creates a new DeleteV1VirtualAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteV1VirtualAccountParams() *DeleteV1VirtualAccountParams {
	return &DeleteV1VirtualAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteV1VirtualAccountParamsWithTimeout creates a new DeleteV1VirtualAccountParams object
// with the ability to set a timeout on a request.
func NewDeleteV1VirtualAccountParamsWithTimeout(timeout time.Duration) *DeleteV1VirtualAccountParams {
	return &DeleteV1VirtualAccountParams{
		timeout: timeout,
	}
}

// NewDeleteV1VirtualAccountParamsWithContext creates a new DeleteV1VirtualAccountParams object
// with the ability to set a context for a request.
func NewDeleteV1VirtualAccountParamsWithContext(ctx context.Context) *DeleteV1VirtualAccountParams {
	return &DeleteV1VirtualAccountParams{
		Context: ctx,
	}
}

// NewDeleteV1VirtualAccountParamsWithHTTPClient creates a new DeleteV1VirtualAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteV1VirtualAccountParamsWithHTTPClient(client *http.Client) *DeleteV1VirtualAccountParams {
	return &DeleteV1VirtualAccountParams{
		HTTPClient: client,
	}
}

/*
DeleteV1VirtualAccountParams contains all the parameters to send to the API endpoint

	for the delete v1 virtual account operation.

	Typically these are written to a http.Request.
*/
type DeleteV1VirtualAccountParams struct {

	/* CHANNELID.

	   Channel ID
	*/
	CHANNELID string

	/* XEXTERNALID.

	   External ID
	*/
	XEXTERNALID string

	/* XSIGNATURE.

	   Request signature
	*/
	XSIGNATURE string

	/* XTIMESTAMP.

	   Request timestamp
	*/
	XTIMESTAMP string

	/* Body.

	   Virtual Account Request
	*/
	Body *models.DeleteVirtualAccountRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete v1 virtual account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteV1VirtualAccountParams) WithDefaults() *DeleteV1VirtualAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete v1 virtual account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteV1VirtualAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) WithTimeout(timeout time.Duration) *DeleteV1VirtualAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) WithContext(ctx context.Context) *DeleteV1VirtualAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) WithHTTPClient(client *http.Client) *DeleteV1VirtualAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCHANNELID adds the cHANNELID to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) WithCHANNELID(cHANNELID string) *DeleteV1VirtualAccountParams {
	o.SetCHANNELID(cHANNELID)
	return o
}

// SetCHANNELID adds the cHANNELId to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) SetCHANNELID(cHANNELID string) {
	o.CHANNELID = cHANNELID
}

// WithXEXTERNALID adds the xEXTERNALID to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) WithXEXTERNALID(xEXTERNALID string) *DeleteV1VirtualAccountParams {
	o.SetXEXTERNALID(xEXTERNALID)
	return o
}

// SetXEXTERNALID adds the xEXTERNALId to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) SetXEXTERNALID(xEXTERNALID string) {
	o.XEXTERNALID = xEXTERNALID
}

// WithXSIGNATURE adds the xSIGNATURE to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) WithXSIGNATURE(xSIGNATURE string) *DeleteV1VirtualAccountParams {
	o.SetXSIGNATURE(xSIGNATURE)
	return o
}

// SetXSIGNATURE adds the xSIGNATURE to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) SetXSIGNATURE(xSIGNATURE string) {
	o.XSIGNATURE = xSIGNATURE
}

// WithXTIMESTAMP adds the xTIMESTAMP to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) WithXTIMESTAMP(xTIMESTAMP string) *DeleteV1VirtualAccountParams {
	o.SetXTIMESTAMP(xTIMESTAMP)
	return o
}

// SetXTIMESTAMP adds the xTIMESTAMP to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) SetXTIMESTAMP(xTIMESTAMP string) {
	o.XTIMESTAMP = xTIMESTAMP
}

// WithBody adds the body to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) WithBody(body *models.DeleteVirtualAccountRequest) *DeleteV1VirtualAccountParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete v1 virtual account params
func (o *DeleteV1VirtualAccountParams) SetBody(body *models.DeleteVirtualAccountRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteV1VirtualAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param CHANNEL-ID
	if err := r.SetHeaderParam("CHANNEL-ID", o.CHANNELID); err != nil {
		return err
	}

	// header param X-EXTERNAL-ID
	if err := r.SetHeaderParam("X-EXTERNAL-ID", o.XEXTERNALID); err != nil {
		return err
	}

	// header param X-SIGNATURE
	if err := r.SetHeaderParam("X-SIGNATURE", o.XSIGNATURE); err != nil {
		return err
	}

	// header param X-TIMESTAMP
	if err := r.SetHeaderParam("X-TIMESTAMP", o.XTIMESTAMP); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
