// Code generated by go-swagger; DO NOT EDIT.

package virtual_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/automotechnologies/doitpay-go/models"
)

// NewDeleteVaV10TransferVaDeleteVaParams creates a new DeleteVaV10TransferVaDeleteVaParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteVaV10TransferVaDeleteVaParams() *DeleteVaV10TransferVaDeleteVaParams {
	return &DeleteVaV10TransferVaDeleteVaParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteVaV10TransferVaDeleteVaParamsWithTimeout creates a new DeleteVaV10TransferVaDeleteVaParams object
// with the ability to set a timeout on a request.
func NewDeleteVaV10TransferVaDeleteVaParamsWithTimeout(timeout time.Duration) *DeleteVaV10TransferVaDeleteVaParams {
	return &DeleteVaV10TransferVaDeleteVaParams{
		timeout: timeout,
	}
}

// NewDeleteVaV10TransferVaDeleteVaParamsWithContext creates a new DeleteVaV10TransferVaDeleteVaParams object
// with the ability to set a context for a request.
func NewDeleteVaV10TransferVaDeleteVaParamsWithContext(ctx context.Context) *DeleteVaV10TransferVaDeleteVaParams {
	return &DeleteVaV10TransferVaDeleteVaParams{
		Context: ctx,
	}
}

// NewDeleteVaV10TransferVaDeleteVaParamsWithHTTPClient creates a new DeleteVaV10TransferVaDeleteVaParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteVaV10TransferVaDeleteVaParamsWithHTTPClient(client *http.Client) *DeleteVaV10TransferVaDeleteVaParams {
	return &DeleteVaV10TransferVaDeleteVaParams{
		HTTPClient: client,
	}
}

/*
DeleteVaV10TransferVaDeleteVaParams contains all the parameters to send to the API endpoint

	for the delete va v10 transfer va delete va operation.

	Typically these are written to a http.Request.
*/
type DeleteVaV10TransferVaDeleteVaParams struct {

	/* CHANNELID.

	   Channel ID
	*/
	CHANNELID string

	/* XEXTERNALID.

	   External ID
	*/
	XEXTERNALID string

	/* XSIGNATURE.

	   Request signature
	*/
	XSIGNATURE string

	/* XTIMESTAMP.

	   Request timestamp
	*/
	XTIMESTAMP string

	/* Body.

	   Virtual Account Request
	*/
	Body *models.DeleteVirtualAccountRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete va v10 transfer va delete va params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteVaV10TransferVaDeleteVaParams) WithDefaults() *DeleteVaV10TransferVaDeleteVaParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete va v10 transfer va delete va params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteVaV10TransferVaDeleteVaParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete va v10 transfer va delete va params
func (o *DeleteVaV10TransferVaDeleteVaParams) WithTimeout(timeout time.Duration) *DeleteVaV10TransferVaDeleteVaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete va v10 transfer va delete va params
func (o *DeleteVaV10TransferVaDeleteVaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete va v10 transfer va delete va params
func (o *DeleteVaV10TransferVaDeleteVaParams) WithContext(ctx context.Context) *DeleteVaV10TransferVaDeleteVaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete va v10 transfer va delete va params
func (o *DeleteVaV10TransferVaDeleteVaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete va v10 transfer va delete va params
func (o *DeleteVaV10TransferVaDeleteVaParams) WithHTTPClient(client *http.Client) *DeleteVaV10TransferVaDeleteVaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete va v10 transfer va delete va params
func (o *DeleteVaV10TransferVaDeleteVaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCHANNELID adds the cHANNELID to the delete va v10 transfer va delete va params
func (o *DeleteVaV10TransferVaDeleteVaParams) WithCHANNELID(cHANNELID string) *DeleteVaV10TransferVaDeleteVaParams {
	o.SetCHANNELID(cHANNELID)
	return o
}

// SetCHANNELID adds the cHANNELId to the delete va v10 transfer va delete va params
func (o *DeleteVaV10TransferVaDeleteVaParams) SetCHANNELID(cHANNELID string) {
	o.CHANNELID = cHANNELID
}

// WithXEXTERNALID adds the xEXTERNALID to the delete va v10 transfer va delete va params
func (o *DeleteVaV10TransferVaDeleteVaParams) WithXEXTERNALID(xEXTERNALID string) *DeleteVaV10TransferVaDeleteVaParams {
	o.SetXEXTERNALID(xEXTERNALID)
	return o
}

// SetXEXTERNALID adds the xEXTERNALId to the delete va v10 transfer va delete va params
func (o *DeleteVaV10TransferVaDeleteVaParams) SetXEXTERNALID(xEXTERNALID string) {
	o.XEXTERNALID = xEXTERNALID
}

// WithXSIGNATURE adds the xSIGNATURE to the delete va v10 transfer va delete va params
func (o *DeleteVaV10TransferVaDeleteVaParams) WithXSIGNATURE(xSIGNATURE string) *DeleteVaV10TransferVaDeleteVaParams {
	o.SetXSIGNATURE(xSIGNATURE)
	return o
}

// SetXSIGNATURE adds the xSIGNATURE to the delete va v10 transfer va delete va params
func (o *DeleteVaV10TransferVaDeleteVaParams) SetXSIGNATURE(xSIGNATURE string) {
	o.XSIGNATURE = xSIGNATURE
}

// WithXTIMESTAMP adds the xTIMESTAMP to the delete va v10 transfer va delete va params
func (o *DeleteVaV10TransferVaDeleteVaParams) WithXTIMESTAMP(xTIMESTAMP string) *DeleteVaV10TransferVaDeleteVaParams {
	o.SetXTIMESTAMP(xTIMESTAMP)
	return o
}

// SetXTIMESTAMP adds the xTIMESTAMP to the delete va v10 transfer va delete va params
func (o *DeleteVaV10TransferVaDeleteVaParams) SetXTIMESTAMP(xTIMESTAMP string) {
	o.XTIMESTAMP = xTIMESTAMP
}

// WithBody adds the body to the delete va v10 transfer va delete va params
func (o *DeleteVaV10TransferVaDeleteVaParams) WithBody(body *models.DeleteVirtualAccountRequest) *DeleteVaV10TransferVaDeleteVaParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete va v10 transfer va delete va params
func (o *DeleteVaV10TransferVaDeleteVaParams) SetBody(body *models.DeleteVirtualAccountRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteVaV10TransferVaDeleteVaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param CHANNEL-ID
	if err := r.SetHeaderParam("CHANNEL-ID", o.CHANNELID); err != nil {
		return err
	}

	// header param X-EXTERNAL-ID
	if err := r.SetHeaderParam("X-EXTERNAL-ID", o.XEXTERNALID); err != nil {
		return err
	}

	// header param X-SIGNATURE
	if err := r.SetHeaderParam("X-SIGNATURE", o.XSIGNATURE); err != nil {
		return err
	}

	// header param X-TIMESTAMP
	if err := r.SetHeaderParam("X-TIMESTAMP", o.XTIMESTAMP); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
