// Code generated by go-swagger; DO NOT EDIT.

package virtual_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/automotechnologies/doitpay-go/models"
)

// NewPostV1VirtualAccountInquiryParams creates a new PostV1VirtualAccountInquiryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1VirtualAccountInquiryParams() *PostV1VirtualAccountInquiryParams {
	return &PostV1VirtualAccountInquiryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1VirtualAccountInquiryParamsWithTimeout creates a new PostV1VirtualAccountInquiryParams object
// with the ability to set a timeout on a request.
func NewPostV1VirtualAccountInquiryParamsWithTimeout(timeout time.Duration) *PostV1VirtualAccountInquiryParams {
	return &PostV1VirtualAccountInquiryParams{
		timeout: timeout,
	}
}

// NewPostV1VirtualAccountInquiryParamsWithContext creates a new PostV1VirtualAccountInquiryParams object
// with the ability to set a context for a request.
func NewPostV1VirtualAccountInquiryParamsWithContext(ctx context.Context) *PostV1VirtualAccountInquiryParams {
	return &PostV1VirtualAccountInquiryParams{
		Context: ctx,
	}
}

// NewPostV1VirtualAccountInquiryParamsWithHTTPClient creates a new PostV1VirtualAccountInquiryParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1VirtualAccountInquiryParamsWithHTTPClient(client *http.Client) *PostV1VirtualAccountInquiryParams {
	return &PostV1VirtualAccountInquiryParams{
		HTTPClient: client,
	}
}

/*
PostV1VirtualAccountInquiryParams contains all the parameters to send to the API endpoint

	for the post v1 virtual account inquiry operation.

	Typically these are written to a http.Request.
*/
type PostV1VirtualAccountInquiryParams struct {

	/* XCLIENTKEY.

	   Client Key
	*/
	XCLIENTKEY string

	/* Body.

	   Virtual Account Request
	*/
	Body *models.Apiv1InquiryVirtualAccountRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1 virtual account inquiry params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1VirtualAccountInquiryParams) WithDefaults() *PostV1VirtualAccountInquiryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1 virtual account inquiry params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1VirtualAccountInquiryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1 virtual account inquiry params
func (o *PostV1VirtualAccountInquiryParams) WithTimeout(timeout time.Duration) *PostV1VirtualAccountInquiryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 virtual account inquiry params
func (o *PostV1VirtualAccountInquiryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 virtual account inquiry params
func (o *PostV1VirtualAccountInquiryParams) WithContext(ctx context.Context) *PostV1VirtualAccountInquiryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 virtual account inquiry params
func (o *PostV1VirtualAccountInquiryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 virtual account inquiry params
func (o *PostV1VirtualAccountInquiryParams) WithHTTPClient(client *http.Client) *PostV1VirtualAccountInquiryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 virtual account inquiry params
func (o *PostV1VirtualAccountInquiryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCLIENTKEY adds the xCLIENTKEY to the post v1 virtual account inquiry params
func (o *PostV1VirtualAccountInquiryParams) WithXCLIENTKEY(xCLIENTKEY string) *PostV1VirtualAccountInquiryParams {
	o.SetXCLIENTKEY(xCLIENTKEY)
	return o
}

// SetXCLIENTKEY adds the xCLIENTKEY to the post v1 virtual account inquiry params
func (o *PostV1VirtualAccountInquiryParams) SetXCLIENTKEY(xCLIENTKEY string) {
	o.XCLIENTKEY = xCLIENTKEY
}

// WithBody adds the body to the post v1 virtual account inquiry params
func (o *PostV1VirtualAccountInquiryParams) WithBody(body *models.Apiv1InquiryVirtualAccountRequest) *PostV1VirtualAccountInquiryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post v1 virtual account inquiry params
func (o *PostV1VirtualAccountInquiryParams) SetBody(body *models.Apiv1InquiryVirtualAccountRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1VirtualAccountInquiryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-CLIENT-KEY
	if err := r.SetHeaderParam("X-CLIENT-KEY", o.XCLIENTKEY); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
