/*
Doitpay API

Testing PublicSimulateAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package doitpay

import (
	"context"
	"os"
	"testing"

	"github.com/automotechnologies/doitpay-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_doitpay_PublicSimulateAPIService(t *testing.T) {

	apiKey := os.Getenv("DTP_APIKEY")
	if apiKey == "" {
		t.Skip("DTP_APIKEY not set")
	}

	apiClient := doitpay.NewClient(apiKey)

	t.Run("Test SimulateApiService SimulatePayment", func(t *testing.T) {

		httpRes, err := apiClient.SimulateAPI.SimulatePayment(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
