// Code generated by go-swagger; DO NOT EDIT.

package debit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/automotechnologies/doitpay-go/models"
)

// NewPostAPIV10DebitStatusParams creates a new PostAPIV10DebitStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV10DebitStatusParams() *PostAPIV10DebitStatusParams {
	return &PostAPIV10DebitStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV10DebitStatusParamsWithTimeout creates a new PostAPIV10DebitStatusParams object
// with the ability to set a timeout on a request.
func NewPostAPIV10DebitStatusParamsWithTimeout(timeout time.Duration) *PostAPIV10DebitStatusParams {
	return &PostAPIV10DebitStatusParams{
		timeout: timeout,
	}
}

// NewPostAPIV10DebitStatusParamsWithContext creates a new PostAPIV10DebitStatusParams object
// with the ability to set a context for a request.
func NewPostAPIV10DebitStatusParamsWithContext(ctx context.Context) *PostAPIV10DebitStatusParams {
	return &PostAPIV10DebitStatusParams{
		Context: ctx,
	}
}

// NewPostAPIV10DebitStatusParamsWithHTTPClient creates a new PostAPIV10DebitStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV10DebitStatusParamsWithHTTPClient(client *http.Client) *PostAPIV10DebitStatusParams {
	return &PostAPIV10DebitStatusParams{
		HTTPClient: client,
	}
}

/*
PostAPIV10DebitStatusParams contains all the parameters to send to the API endpoint

	for the post API v10 debit status operation.

	Typically these are written to a http.Request.
*/
type PostAPIV10DebitStatusParams struct {

	/* CHANNELID.

	   Channel ID
	*/
	CHANNELID string

	/* Request.

	   Status check request
	*/
	Request *models.CheckPaymentStatusEwalletRequest

	/* XEXTERNALID.

	   External ID
	*/
	XEXTERNALID string

	/* XPARTNERID.

	   Partner ID
	*/
	XPARTNERID string

	/* XREQUESTID.

	   Request ID
	*/
	XREQUESTID string

	/* XSIGNATURE.

	   Request signature
	*/
	XSIGNATURE string

	/* XTIMESTAMP.

	   Request timestamp
	*/
	XTIMESTAMP string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v10 debit status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV10DebitStatusParams) WithDefaults() *PostAPIV10DebitStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v10 debit status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV10DebitStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) WithTimeout(timeout time.Duration) *PostAPIV10DebitStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) WithContext(ctx context.Context) *PostAPIV10DebitStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) WithHTTPClient(client *http.Client) *PostAPIV10DebitStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCHANNELID adds the cHANNELID to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) WithCHANNELID(cHANNELID string) *PostAPIV10DebitStatusParams {
	o.SetCHANNELID(cHANNELID)
	return o
}

// SetCHANNELID adds the cHANNELId to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) SetCHANNELID(cHANNELID string) {
	o.CHANNELID = cHANNELID
}

// WithRequest adds the request to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) WithRequest(request *models.CheckPaymentStatusEwalletRequest) *PostAPIV10DebitStatusParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) SetRequest(request *models.CheckPaymentStatusEwalletRequest) {
	o.Request = request
}

// WithXEXTERNALID adds the xEXTERNALID to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) WithXEXTERNALID(xEXTERNALID string) *PostAPIV10DebitStatusParams {
	o.SetXEXTERNALID(xEXTERNALID)
	return o
}

// SetXEXTERNALID adds the xEXTERNALId to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) SetXEXTERNALID(xEXTERNALID string) {
	o.XEXTERNALID = xEXTERNALID
}

// WithXPARTNERID adds the xPARTNERID to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) WithXPARTNERID(xPARTNERID string) *PostAPIV10DebitStatusParams {
	o.SetXPARTNERID(xPARTNERID)
	return o
}

// SetXPARTNERID adds the xPARTNERId to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) SetXPARTNERID(xPARTNERID string) {
	o.XPARTNERID = xPARTNERID
}

// WithXREQUESTID adds the xREQUESTID to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) WithXREQUESTID(xREQUESTID string) *PostAPIV10DebitStatusParams {
	o.SetXREQUESTID(xREQUESTID)
	return o
}

// SetXREQUESTID adds the xREQUESTId to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) SetXREQUESTID(xREQUESTID string) {
	o.XREQUESTID = xREQUESTID
}

// WithXSIGNATURE adds the xSIGNATURE to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) WithXSIGNATURE(xSIGNATURE string) *PostAPIV10DebitStatusParams {
	o.SetXSIGNATURE(xSIGNATURE)
	return o
}

// SetXSIGNATURE adds the xSIGNATURE to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) SetXSIGNATURE(xSIGNATURE string) {
	o.XSIGNATURE = xSIGNATURE
}

// WithXTIMESTAMP adds the xTIMESTAMP to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) WithXTIMESTAMP(xTIMESTAMP string) *PostAPIV10DebitStatusParams {
	o.SetXTIMESTAMP(xTIMESTAMP)
	return o
}

// SetXTIMESTAMP adds the xTIMESTAMP to the post API v10 debit status params
func (o *PostAPIV10DebitStatusParams) SetXTIMESTAMP(xTIMESTAMP string) {
	o.XTIMESTAMP = xTIMESTAMP
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV10DebitStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param CHANNEL-ID
	if err := r.SetHeaderParam("CHANNEL-ID", o.CHANNELID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// header param X-EXTERNAL-ID
	if err := r.SetHeaderParam("X-EXTERNAL-ID", o.XEXTERNALID); err != nil {
		return err
	}

	// header param X-PARTNER-ID
	if err := r.SetHeaderParam("X-PARTNER-ID", o.XPARTNERID); err != nil {
		return err
	}

	// header param X-REQUEST-ID
	if err := r.SetHeaderParam("X-REQUEST-ID", o.XREQUESTID); err != nil {
		return err
	}

	// header param X-SIGNATURE
	if err := r.SetHeaderParam("X-SIGNATURE", o.XSIGNATURE); err != nil {
		return err
	}

	// header param X-TIMESTAMP
	if err := r.SetHeaderParam("X-TIMESTAMP", o.XTIMESTAMP); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
