// Code generated by go-swagger; DO NOT EDIT.

package debit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/automotechnologies/doitpay-go/models"
)

// NewPostAPIDebitV10PaymentHostToHostParams creates a new PostAPIDebitV10PaymentHostToHostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIDebitV10PaymentHostToHostParams() *PostAPIDebitV10PaymentHostToHostParams {
	return &PostAPIDebitV10PaymentHostToHostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIDebitV10PaymentHostToHostParamsWithTimeout creates a new PostAPIDebitV10PaymentHostToHostParams object
// with the ability to set a timeout on a request.
func NewPostAPIDebitV10PaymentHostToHostParamsWithTimeout(timeout time.Duration) *PostAPIDebitV10PaymentHostToHostParams {
	return &PostAPIDebitV10PaymentHostToHostParams{
		timeout: timeout,
	}
}

// NewPostAPIDebitV10PaymentHostToHostParamsWithContext creates a new PostAPIDebitV10PaymentHostToHostParams object
// with the ability to set a context for a request.
func NewPostAPIDebitV10PaymentHostToHostParamsWithContext(ctx context.Context) *PostAPIDebitV10PaymentHostToHostParams {
	return &PostAPIDebitV10PaymentHostToHostParams{
		Context: ctx,
	}
}

// NewPostAPIDebitV10PaymentHostToHostParamsWithHTTPClient creates a new PostAPIDebitV10PaymentHostToHostParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIDebitV10PaymentHostToHostParamsWithHTTPClient(client *http.Client) *PostAPIDebitV10PaymentHostToHostParams {
	return &PostAPIDebitV10PaymentHostToHostParams{
		HTTPClient: client,
	}
}

/*
PostAPIDebitV10PaymentHostToHostParams contains all the parameters to send to the API endpoint

	for the post API debit v10 payment host to host operation.

	Typically these are written to a http.Request.
*/
type PostAPIDebitV10PaymentHostToHostParams struct {

	/* CHANNELID.

	   Channel ID
	*/
	CHANNELID string

	/* Request.

	   Payment request
	*/
	Request *models.CreateEwalletRequest

	/* XEXTERNALID.

	   External ID
	*/
	XEXTERNALID string

	/* XPARTNERID.

	   Partner ID
	*/
	XPARTNERID string

	/* XREQUESTID.

	   Request ID
	*/
	XREQUESTID string

	/* XSIGNATURE.

	   Request signature
	*/
	XSIGNATURE string

	/* XTIMESTAMP.

	   Request timestamp
	*/
	XTIMESTAMP string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API debit v10 payment host to host params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIDebitV10PaymentHostToHostParams) WithDefaults() *PostAPIDebitV10PaymentHostToHostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API debit v10 payment host to host params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIDebitV10PaymentHostToHostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) WithTimeout(timeout time.Duration) *PostAPIDebitV10PaymentHostToHostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) WithContext(ctx context.Context) *PostAPIDebitV10PaymentHostToHostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) WithHTTPClient(client *http.Client) *PostAPIDebitV10PaymentHostToHostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCHANNELID adds the cHANNELID to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) WithCHANNELID(cHANNELID string) *PostAPIDebitV10PaymentHostToHostParams {
	o.SetCHANNELID(cHANNELID)
	return o
}

// SetCHANNELID adds the cHANNELId to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) SetCHANNELID(cHANNELID string) {
	o.CHANNELID = cHANNELID
}

// WithRequest adds the request to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) WithRequest(request *models.CreateEwalletRequest) *PostAPIDebitV10PaymentHostToHostParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) SetRequest(request *models.CreateEwalletRequest) {
	o.Request = request
}

// WithXEXTERNALID adds the xEXTERNALID to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) WithXEXTERNALID(xEXTERNALID string) *PostAPIDebitV10PaymentHostToHostParams {
	o.SetXEXTERNALID(xEXTERNALID)
	return o
}

// SetXEXTERNALID adds the xEXTERNALId to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) SetXEXTERNALID(xEXTERNALID string) {
	o.XEXTERNALID = xEXTERNALID
}

// WithXPARTNERID adds the xPARTNERID to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) WithXPARTNERID(xPARTNERID string) *PostAPIDebitV10PaymentHostToHostParams {
	o.SetXPARTNERID(xPARTNERID)
	return o
}

// SetXPARTNERID adds the xPARTNERId to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) SetXPARTNERID(xPARTNERID string) {
	o.XPARTNERID = xPARTNERID
}

// WithXREQUESTID adds the xREQUESTID to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) WithXREQUESTID(xREQUESTID string) *PostAPIDebitV10PaymentHostToHostParams {
	o.SetXREQUESTID(xREQUESTID)
	return o
}

// SetXREQUESTID adds the xREQUESTId to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) SetXREQUESTID(xREQUESTID string) {
	o.XREQUESTID = xREQUESTID
}

// WithXSIGNATURE adds the xSIGNATURE to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) WithXSIGNATURE(xSIGNATURE string) *PostAPIDebitV10PaymentHostToHostParams {
	o.SetXSIGNATURE(xSIGNATURE)
	return o
}

// SetXSIGNATURE adds the xSIGNATURE to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) SetXSIGNATURE(xSIGNATURE string) {
	o.XSIGNATURE = xSIGNATURE
}

// WithXTIMESTAMP adds the xTIMESTAMP to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) WithXTIMESTAMP(xTIMESTAMP string) *PostAPIDebitV10PaymentHostToHostParams {
	o.SetXTIMESTAMP(xTIMESTAMP)
	return o
}

// SetXTIMESTAMP adds the xTIMESTAMP to the post API debit v10 payment host to host params
func (o *PostAPIDebitV10PaymentHostToHostParams) SetXTIMESTAMP(xTIMESTAMP string) {
	o.XTIMESTAMP = xTIMESTAMP
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIDebitV10PaymentHostToHostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param CHANNEL-ID
	if err := r.SetHeaderParam("CHANNEL-ID", o.CHANNELID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// header param X-EXTERNAL-ID
	if err := r.SetHeaderParam("X-EXTERNAL-ID", o.XEXTERNALID); err != nil {
		return err
	}

	// header param X-PARTNER-ID
	if err := r.SetHeaderParam("X-PARTNER-ID", o.XPARTNERID); err != nil {
		return err
	}

	// header param X-REQUEST-ID
	if err := r.SetHeaderParam("X-REQUEST-ID", o.XREQUESTID); err != nil {
		return err
	}

	// header param X-SIGNATURE
	if err := r.SetHeaderParam("X-SIGNATURE", o.XSIGNATURE); err != nil {
		return err
	}

	// header param X-TIMESTAMP
	if err := r.SetHeaderParam("X-TIMESTAMP", o.XTIMESTAMP); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
