// Code generated by go-swagger; DO NOT EDIT.

package debit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/automotechnologies/doitpay-go/models"
)

// PostAPIV10DebitPaymentHostToHostReader is a Reader for the PostAPIV10DebitPaymentHostToHost structure.
type PostAPIV10DebitPaymentHostToHostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV10DebitPaymentHostToHostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV10DebitPaymentHostToHostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV10DebitPaymentHostToHostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV10DebitPaymentHostToHostUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostAPIV10DebitPaymentHostToHostConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV10DebitPaymentHostToHostInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1.0/debit/payment-host-to-host] PostAPIV10DebitPaymentHostToHost", response, response.Code())
	}
}

// NewPostAPIV10DebitPaymentHostToHostOK creates a PostAPIV10DebitPaymentHostToHostOK with default headers values
func NewPostAPIV10DebitPaymentHostToHostOK() *PostAPIV10DebitPaymentHostToHostOK {
	return &PostAPIV10DebitPaymentHostToHostOK{}
}

/*
PostAPIV10DebitPaymentHostToHostOK describes a response with status code 200, with default header values.

OK
*/
type PostAPIV10DebitPaymentHostToHostOK struct {
	Payload *models.CreateEwalletResponse
}

// IsSuccess returns true when this post Api v10 debit payment host to host o k response has a 2xx status code
func (o *PostAPIV10DebitPaymentHostToHostOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v10 debit payment host to host o k response has a 3xx status code
func (o *PostAPIV10DebitPaymentHostToHostOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v10 debit payment host to host o k response has a 4xx status code
func (o *PostAPIV10DebitPaymentHostToHostOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v10 debit payment host to host o k response has a 5xx status code
func (o *PostAPIV10DebitPaymentHostToHostOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v10 debit payment host to host o k response a status code equal to that given
func (o *PostAPIV10DebitPaymentHostToHostOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v10 debit payment host to host o k response
func (o *PostAPIV10DebitPaymentHostToHostOK) Code() int {
	return 200
}

func (o *PostAPIV10DebitPaymentHostToHostOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1.0/debit/payment-host-to-host][%d] postApiV10DebitPaymentHostToHostOK %s", 200, payload)
}

func (o *PostAPIV10DebitPaymentHostToHostOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1.0/debit/payment-host-to-host][%d] postApiV10DebitPaymentHostToHostOK %s", 200, payload)
}

func (o *PostAPIV10DebitPaymentHostToHostOK) GetPayload() *models.CreateEwalletResponse {
	return o.Payload
}

func (o *PostAPIV10DebitPaymentHostToHostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateEwalletResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10DebitPaymentHostToHostBadRequest creates a PostAPIV10DebitPaymentHostToHostBadRequest with default headers values
func NewPostAPIV10DebitPaymentHostToHostBadRequest() *PostAPIV10DebitPaymentHostToHostBadRequest {
	return &PostAPIV10DebitPaymentHostToHostBadRequest{}
}

/*
PostAPIV10DebitPaymentHostToHostBadRequest describes a response with status code 400, with default header values.

Invalid request parameters
*/
type PostAPIV10DebitPaymentHostToHostBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this post Api v10 debit payment host to host bad request response has a 2xx status code
func (o *PostAPIV10DebitPaymentHostToHostBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v10 debit payment host to host bad request response has a 3xx status code
func (o *PostAPIV10DebitPaymentHostToHostBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v10 debit payment host to host bad request response has a 4xx status code
func (o *PostAPIV10DebitPaymentHostToHostBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v10 debit payment host to host bad request response has a 5xx status code
func (o *PostAPIV10DebitPaymentHostToHostBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v10 debit payment host to host bad request response a status code equal to that given
func (o *PostAPIV10DebitPaymentHostToHostBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v10 debit payment host to host bad request response
func (o *PostAPIV10DebitPaymentHostToHostBadRequest) Code() int {
	return 400
}

func (o *PostAPIV10DebitPaymentHostToHostBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1.0/debit/payment-host-to-host][%d] postApiV10DebitPaymentHostToHostBadRequest %s", 400, payload)
}

func (o *PostAPIV10DebitPaymentHostToHostBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1.0/debit/payment-host-to-host][%d] postApiV10DebitPaymentHostToHostBadRequest %s", 400, payload)
}

func (o *PostAPIV10DebitPaymentHostToHostBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *PostAPIV10DebitPaymentHostToHostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10DebitPaymentHostToHostUnauthorized creates a PostAPIV10DebitPaymentHostToHostUnauthorized with default headers values
func NewPostAPIV10DebitPaymentHostToHostUnauthorized() *PostAPIV10DebitPaymentHostToHostUnauthorized {
	return &PostAPIV10DebitPaymentHostToHostUnauthorized{}
}

/*
PostAPIV10DebitPaymentHostToHostUnauthorized describes a response with status code 401, with default header values.

Authentication failed
*/
type PostAPIV10DebitPaymentHostToHostUnauthorized struct {
	Payload interface{}
}

// IsSuccess returns true when this post Api v10 debit payment host to host unauthorized response has a 2xx status code
func (o *PostAPIV10DebitPaymentHostToHostUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v10 debit payment host to host unauthorized response has a 3xx status code
func (o *PostAPIV10DebitPaymentHostToHostUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v10 debit payment host to host unauthorized response has a 4xx status code
func (o *PostAPIV10DebitPaymentHostToHostUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v10 debit payment host to host unauthorized response has a 5xx status code
func (o *PostAPIV10DebitPaymentHostToHostUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v10 debit payment host to host unauthorized response a status code equal to that given
func (o *PostAPIV10DebitPaymentHostToHostUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v10 debit payment host to host unauthorized response
func (o *PostAPIV10DebitPaymentHostToHostUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV10DebitPaymentHostToHostUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1.0/debit/payment-host-to-host][%d] postApiV10DebitPaymentHostToHostUnauthorized %s", 401, payload)
}

func (o *PostAPIV10DebitPaymentHostToHostUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1.0/debit/payment-host-to-host][%d] postApiV10DebitPaymentHostToHostUnauthorized %s", 401, payload)
}

func (o *PostAPIV10DebitPaymentHostToHostUnauthorized) GetPayload() interface{} {
	return o.Payload
}

func (o *PostAPIV10DebitPaymentHostToHostUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10DebitPaymentHostToHostConflict creates a PostAPIV10DebitPaymentHostToHostConflict with default headers values
func NewPostAPIV10DebitPaymentHostToHostConflict() *PostAPIV10DebitPaymentHostToHostConflict {
	return &PostAPIV10DebitPaymentHostToHostConflict{}
}

/*
PostAPIV10DebitPaymentHostToHostConflict describes a response with status code 409, with default header values.

Duplicate transaction
*/
type PostAPIV10DebitPaymentHostToHostConflict struct {
	Payload interface{}
}

// IsSuccess returns true when this post Api v10 debit payment host to host conflict response has a 2xx status code
func (o *PostAPIV10DebitPaymentHostToHostConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v10 debit payment host to host conflict response has a 3xx status code
func (o *PostAPIV10DebitPaymentHostToHostConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v10 debit payment host to host conflict response has a 4xx status code
func (o *PostAPIV10DebitPaymentHostToHostConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v10 debit payment host to host conflict response has a 5xx status code
func (o *PostAPIV10DebitPaymentHostToHostConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v10 debit payment host to host conflict response a status code equal to that given
func (o *PostAPIV10DebitPaymentHostToHostConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the post Api v10 debit payment host to host conflict response
func (o *PostAPIV10DebitPaymentHostToHostConflict) Code() int {
	return 409
}

func (o *PostAPIV10DebitPaymentHostToHostConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1.0/debit/payment-host-to-host][%d] postApiV10DebitPaymentHostToHostConflict %s", 409, payload)
}

func (o *PostAPIV10DebitPaymentHostToHostConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1.0/debit/payment-host-to-host][%d] postApiV10DebitPaymentHostToHostConflict %s", 409, payload)
}

func (o *PostAPIV10DebitPaymentHostToHostConflict) GetPayload() interface{} {
	return o.Payload
}

func (o *PostAPIV10DebitPaymentHostToHostConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV10DebitPaymentHostToHostInternalServerError creates a PostAPIV10DebitPaymentHostToHostInternalServerError with default headers values
func NewPostAPIV10DebitPaymentHostToHostInternalServerError() *PostAPIV10DebitPaymentHostToHostInternalServerError {
	return &PostAPIV10DebitPaymentHostToHostInternalServerError{}
}

/*
PostAPIV10DebitPaymentHostToHostInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type PostAPIV10DebitPaymentHostToHostInternalServerError struct {
	Payload interface{}
}

// IsSuccess returns true when this post Api v10 debit payment host to host internal server error response has a 2xx status code
func (o *PostAPIV10DebitPaymentHostToHostInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v10 debit payment host to host internal server error response has a 3xx status code
func (o *PostAPIV10DebitPaymentHostToHostInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v10 debit payment host to host internal server error response has a 4xx status code
func (o *PostAPIV10DebitPaymentHostToHostInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v10 debit payment host to host internal server error response has a 5xx status code
func (o *PostAPIV10DebitPaymentHostToHostInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v10 debit payment host to host internal server error response a status code equal to that given
func (o *PostAPIV10DebitPaymentHostToHostInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v10 debit payment host to host internal server error response
func (o *PostAPIV10DebitPaymentHostToHostInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV10DebitPaymentHostToHostInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1.0/debit/payment-host-to-host][%d] postApiV10DebitPaymentHostToHostInternalServerError %s", 500, payload)
}

func (o *PostAPIV10DebitPaymentHostToHostInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1.0/debit/payment-host-to-host][%d] postApiV10DebitPaymentHostToHostInternalServerError %s", 500, payload)
}

func (o *PostAPIV10DebitPaymentHostToHostInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *PostAPIV10DebitPaymentHostToHostInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
