// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/automotechnologies/doitpay-go/models"
)

// NewMerchantAPIAccessTokenParams creates a new MerchantAPIAccessTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMerchantAPIAccessTokenParams() *MerchantAPIAccessTokenParams {
	return &MerchantAPIAccessTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMerchantAPIAccessTokenParamsWithTimeout creates a new MerchantAPIAccessTokenParams object
// with the ability to set a timeout on a request.
func NewMerchantAPIAccessTokenParamsWithTimeout(timeout time.Duration) *MerchantAPIAccessTokenParams {
	return &MerchantAPIAccessTokenParams{
		timeout: timeout,
	}
}

// NewMerchantAPIAccessTokenParamsWithContext creates a new MerchantAPIAccessTokenParams object
// with the ability to set a context for a request.
func NewMerchantAPIAccessTokenParamsWithContext(ctx context.Context) *MerchantAPIAccessTokenParams {
	return &MerchantAPIAccessTokenParams{
		Context: ctx,
	}
}

// NewMerchantAPIAccessTokenParamsWithHTTPClient creates a new MerchantAPIAccessTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewMerchantAPIAccessTokenParamsWithHTTPClient(client *http.Client) *MerchantAPIAccessTokenParams {
	return &MerchantAPIAccessTokenParams{
		HTTPClient: client,
	}
}

/*
MerchantAPIAccessTokenParams contains all the parameters to send to the API endpoint

	for the merchant api access token operation.

	Typically these are written to a http.Request.
*/
type MerchantAPIAccessTokenParams struct {

	/* Request.

	   Access token request
	*/
	Request *models.Apiv1PartnerAccessTokenRequest

	/* XCLIENTKEY.

	   Client Key
	*/
	XCLIENTKEY string

	/* XSIGNATURE.

	   Request signature
	*/
	XSIGNATURE string

	/* XTIMESTAMP.

	   Request timestamp
	*/
	XTIMESTAMP string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the merchant api access token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MerchantAPIAccessTokenParams) WithDefaults() *MerchantAPIAccessTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the merchant api access token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MerchantAPIAccessTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the merchant api access token params
func (o *MerchantAPIAccessTokenParams) WithTimeout(timeout time.Duration) *MerchantAPIAccessTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the merchant api access token params
func (o *MerchantAPIAccessTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the merchant api access token params
func (o *MerchantAPIAccessTokenParams) WithContext(ctx context.Context) *MerchantAPIAccessTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the merchant api access token params
func (o *MerchantAPIAccessTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the merchant api access token params
func (o *MerchantAPIAccessTokenParams) WithHTTPClient(client *http.Client) *MerchantAPIAccessTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the merchant api access token params
func (o *MerchantAPIAccessTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the merchant api access token params
func (o *MerchantAPIAccessTokenParams) WithRequest(request *models.Apiv1PartnerAccessTokenRequest) *MerchantAPIAccessTokenParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the merchant api access token params
func (o *MerchantAPIAccessTokenParams) SetRequest(request *models.Apiv1PartnerAccessTokenRequest) {
	o.Request = request
}

// WithXCLIENTKEY adds the xCLIENTKEY to the merchant api access token params
func (o *MerchantAPIAccessTokenParams) WithXCLIENTKEY(xCLIENTKEY string) *MerchantAPIAccessTokenParams {
	o.SetXCLIENTKEY(xCLIENTKEY)
	return o
}

// SetXCLIENTKEY adds the xCLIENTKEY to the merchant api access token params
func (o *MerchantAPIAccessTokenParams) SetXCLIENTKEY(xCLIENTKEY string) {
	o.XCLIENTKEY = xCLIENTKEY
}

// WithXSIGNATURE adds the xSIGNATURE to the merchant api access token params
func (o *MerchantAPIAccessTokenParams) WithXSIGNATURE(xSIGNATURE string) *MerchantAPIAccessTokenParams {
	o.SetXSIGNATURE(xSIGNATURE)
	return o
}

// SetXSIGNATURE adds the xSIGNATURE to the merchant api access token params
func (o *MerchantAPIAccessTokenParams) SetXSIGNATURE(xSIGNATURE string) {
	o.XSIGNATURE = xSIGNATURE
}

// WithXTIMESTAMP adds the xTIMESTAMP to the merchant api access token params
func (o *MerchantAPIAccessTokenParams) WithXTIMESTAMP(xTIMESTAMP string) *MerchantAPIAccessTokenParams {
	o.SetXTIMESTAMP(xTIMESTAMP)
	return o
}

// SetXTIMESTAMP adds the xTIMESTAMP to the merchant api access token params
func (o *MerchantAPIAccessTokenParams) SetXTIMESTAMP(xTIMESTAMP string) {
	o.XTIMESTAMP = xTIMESTAMP
}

// WriteToRequest writes these params to a swagger request
func (o *MerchantAPIAccessTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// header param X-CLIENT-KEY
	if err := r.SetHeaderParam("X-CLIENT-KEY", o.XCLIENTKEY); err != nil {
		return err
	}

	// header param X-SIGNATURE
	if err := r.SetHeaderParam("X-SIGNATURE", o.XSIGNATURE); err != nil {
		return err
	}

	// header param X-TIMESTAMP
	if err := r.SetHeaderParam("X-TIMESTAMP", o.XTIMESTAMP); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
