// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAuthV10UtilitiesSignatureAuthParams creates a new PostAuthV10UtilitiesSignatureAuthParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAuthV10UtilitiesSignatureAuthParams() *PostAuthV10UtilitiesSignatureAuthParams {
	return &PostAuthV10UtilitiesSignatureAuthParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAuthV10UtilitiesSignatureAuthParamsWithTimeout creates a new PostAuthV10UtilitiesSignatureAuthParams object
// with the ability to set a timeout on a request.
func NewPostAuthV10UtilitiesSignatureAuthParamsWithTimeout(timeout time.Duration) *PostAuthV10UtilitiesSignatureAuthParams {
	return &PostAuthV10UtilitiesSignatureAuthParams{
		timeout: timeout,
	}
}

// NewPostAuthV10UtilitiesSignatureAuthParamsWithContext creates a new PostAuthV10UtilitiesSignatureAuthParams object
// with the ability to set a context for a request.
func NewPostAuthV10UtilitiesSignatureAuthParamsWithContext(ctx context.Context) *PostAuthV10UtilitiesSignatureAuthParams {
	return &PostAuthV10UtilitiesSignatureAuthParams{
		Context: ctx,
	}
}

// NewPostAuthV10UtilitiesSignatureAuthParamsWithHTTPClient creates a new PostAuthV10UtilitiesSignatureAuthParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAuthV10UtilitiesSignatureAuthParamsWithHTTPClient(client *http.Client) *PostAuthV10UtilitiesSignatureAuthParams {
	return &PostAuthV10UtilitiesSignatureAuthParams{
		HTTPClient: client,
	}
}

/*
PostAuthV10UtilitiesSignatureAuthParams contains all the parameters to send to the API endpoint

	for the post auth v10 utilities signature auth operation.

	Typically these are written to a http.Request.
*/
type PostAuthV10UtilitiesSignatureAuthParams struct {

	/* XCLIENTKEY.

	   Client Key
	*/
	XCLIENTKEY string

	/* XTIMESTAMP.

	   Request timestamp in ISO 8601 format
	*/
	XTIMESTAMP string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post auth v10 utilities signature auth params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAuthV10UtilitiesSignatureAuthParams) WithDefaults() *PostAuthV10UtilitiesSignatureAuthParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post auth v10 utilities signature auth params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAuthV10UtilitiesSignatureAuthParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post auth v10 utilities signature auth params
func (o *PostAuthV10UtilitiesSignatureAuthParams) WithTimeout(timeout time.Duration) *PostAuthV10UtilitiesSignatureAuthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post auth v10 utilities signature auth params
func (o *PostAuthV10UtilitiesSignatureAuthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post auth v10 utilities signature auth params
func (o *PostAuthV10UtilitiesSignatureAuthParams) WithContext(ctx context.Context) *PostAuthV10UtilitiesSignatureAuthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post auth v10 utilities signature auth params
func (o *PostAuthV10UtilitiesSignatureAuthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post auth v10 utilities signature auth params
func (o *PostAuthV10UtilitiesSignatureAuthParams) WithHTTPClient(client *http.Client) *PostAuthV10UtilitiesSignatureAuthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post auth v10 utilities signature auth params
func (o *PostAuthV10UtilitiesSignatureAuthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCLIENTKEY adds the xCLIENTKEY to the post auth v10 utilities signature auth params
func (o *PostAuthV10UtilitiesSignatureAuthParams) WithXCLIENTKEY(xCLIENTKEY string) *PostAuthV10UtilitiesSignatureAuthParams {
	o.SetXCLIENTKEY(xCLIENTKEY)
	return o
}

// SetXCLIENTKEY adds the xCLIENTKEY to the post auth v10 utilities signature auth params
func (o *PostAuthV10UtilitiesSignatureAuthParams) SetXCLIENTKEY(xCLIENTKEY string) {
	o.XCLIENTKEY = xCLIENTKEY
}

// WithXTIMESTAMP adds the xTIMESTAMP to the post auth v10 utilities signature auth params
func (o *PostAuthV10UtilitiesSignatureAuthParams) WithXTIMESTAMP(xTIMESTAMP string) *PostAuthV10UtilitiesSignatureAuthParams {
	o.SetXTIMESTAMP(xTIMESTAMP)
	return o
}

// SetXTIMESTAMP adds the xTIMESTAMP to the post auth v10 utilities signature auth params
func (o *PostAuthV10UtilitiesSignatureAuthParams) SetXTIMESTAMP(xTIMESTAMP string) {
	o.XTIMESTAMP = xTIMESTAMP
}

// WriteToRequest writes these params to a swagger request
func (o *PostAuthV10UtilitiesSignatureAuthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-CLIENT-KEY
	if err := r.SetHeaderParam("X-CLIENT-KEY", o.XCLIENTKEY); err != nil {
		return err
	}

	// header param X-TIMESTAMP
	if err := r.SetHeaderParam("X-TIMESTAMP", o.XTIMESTAMP); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
