// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAuthV10AccessTokenB2bParams creates a new PostAuthV10AccessTokenB2bParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAuthV10AccessTokenB2bParams() *PostAuthV10AccessTokenB2bParams {
	return &PostAuthV10AccessTokenB2bParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAuthV10AccessTokenB2bParamsWithTimeout creates a new PostAuthV10AccessTokenB2bParams object
// with the ability to set a timeout on a request.
func NewPostAuthV10AccessTokenB2bParamsWithTimeout(timeout time.Duration) *PostAuthV10AccessTokenB2bParams {
	return &PostAuthV10AccessTokenB2bParams{
		timeout: timeout,
	}
}

// NewPostAuthV10AccessTokenB2bParamsWithContext creates a new PostAuthV10AccessTokenB2bParams object
// with the ability to set a context for a request.
func NewPostAuthV10AccessTokenB2bParamsWithContext(ctx context.Context) *PostAuthV10AccessTokenB2bParams {
	return &PostAuthV10AccessTokenB2bParams{
		Context: ctx,
	}
}

// NewPostAuthV10AccessTokenB2bParamsWithHTTPClient creates a new PostAuthV10AccessTokenB2bParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAuthV10AccessTokenB2bParamsWithHTTPClient(client *http.Client) *PostAuthV10AccessTokenB2bParams {
	return &PostAuthV10AccessTokenB2bParams{
		HTTPClient: client,
	}
}

/*
PostAuthV10AccessTokenB2bParams contains all the parameters to send to the API endpoint

	for the post auth v10 access token b2b operation.

	Typically these are written to a http.Request.
*/
type PostAuthV10AccessTokenB2bParams struct {

	/* XCLIENTKEY.

	   Client Key
	*/
	XCLIENTKEY string

	/* XSIGNATURE.

	   Request signature
	*/
	XSIGNATURE string

	/* XTIMESTAMP.

	   Request timestamp in ISO 8601 format
	*/
	XTIMESTAMP string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post auth v10 access token b2b params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAuthV10AccessTokenB2bParams) WithDefaults() *PostAuthV10AccessTokenB2bParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post auth v10 access token b2b params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAuthV10AccessTokenB2bParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post auth v10 access token b2b params
func (o *PostAuthV10AccessTokenB2bParams) WithTimeout(timeout time.Duration) *PostAuthV10AccessTokenB2bParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post auth v10 access token b2b params
func (o *PostAuthV10AccessTokenB2bParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post auth v10 access token b2b params
func (o *PostAuthV10AccessTokenB2bParams) WithContext(ctx context.Context) *PostAuthV10AccessTokenB2bParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post auth v10 access token b2b params
func (o *PostAuthV10AccessTokenB2bParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post auth v10 access token b2b params
func (o *PostAuthV10AccessTokenB2bParams) WithHTTPClient(client *http.Client) *PostAuthV10AccessTokenB2bParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post auth v10 access token b2b params
func (o *PostAuthV10AccessTokenB2bParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCLIENTKEY adds the xCLIENTKEY to the post auth v10 access token b2b params
func (o *PostAuthV10AccessTokenB2bParams) WithXCLIENTKEY(xCLIENTKEY string) *PostAuthV10AccessTokenB2bParams {
	o.SetXCLIENTKEY(xCLIENTKEY)
	return o
}

// SetXCLIENTKEY adds the xCLIENTKEY to the post auth v10 access token b2b params
func (o *PostAuthV10AccessTokenB2bParams) SetXCLIENTKEY(xCLIENTKEY string) {
	o.XCLIENTKEY = xCLIENTKEY
}

// WithXSIGNATURE adds the xSIGNATURE to the post auth v10 access token b2b params
func (o *PostAuthV10AccessTokenB2bParams) WithXSIGNATURE(xSIGNATURE string) *PostAuthV10AccessTokenB2bParams {
	o.SetXSIGNATURE(xSIGNATURE)
	return o
}

// SetXSIGNATURE adds the xSIGNATURE to the post auth v10 access token b2b params
func (o *PostAuthV10AccessTokenB2bParams) SetXSIGNATURE(xSIGNATURE string) {
	o.XSIGNATURE = xSIGNATURE
}

// WithXTIMESTAMP adds the xTIMESTAMP to the post auth v10 access token b2b params
func (o *PostAuthV10AccessTokenB2bParams) WithXTIMESTAMP(xTIMESTAMP string) *PostAuthV10AccessTokenB2bParams {
	o.SetXTIMESTAMP(xTIMESTAMP)
	return o
}

// SetXTIMESTAMP adds the xTIMESTAMP to the post auth v10 access token b2b params
func (o *PostAuthV10AccessTokenB2bParams) SetXTIMESTAMP(xTIMESTAMP string) {
	o.XTIMESTAMP = xTIMESTAMP
}

// WriteToRequest writes these params to a swagger request
func (o *PostAuthV10AccessTokenB2bParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-CLIENT-KEY
	if err := r.SetHeaderParam("X-CLIENT-KEY", o.XCLIENTKEY); err != nil {
		return err
	}

	// header param X-SIGNATURE
	if err := r.SetHeaderParam("X-SIGNATURE", o.XSIGNATURE); err != nil {
		return err
	}

	// header param X-TIMESTAMP
	if err := r.SetHeaderParam("X-TIMESTAMP", o.XTIMESTAMP); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
