// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/automotechnologies/doitpay-go/models"
)

// PostAuthV10AccessTokenB2bReader is a Reader for the PostAuthV10AccessTokenB2b structure.
type PostAuthV10AccessTokenB2bReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAuthV10AccessTokenB2bReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAuthV10AccessTokenB2bOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAuthV10AccessTokenB2bBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAuthV10AccessTokenB2bUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAuthV10AccessTokenB2bInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /auth/v1.0/access-token/b2b] PostAuthV10AccessTokenB2b", response, response.Code())
	}
}

// NewPostAuthV10AccessTokenB2bOK creates a PostAuthV10AccessTokenB2bOK with default headers values
func NewPostAuthV10AccessTokenB2bOK() *PostAuthV10AccessTokenB2bOK {
	return &PostAuthV10AccessTokenB2bOK{}
}

/*
PostAuthV10AccessTokenB2bOK describes a response with status code 200, with default header values.

OK
*/
type PostAuthV10AccessTokenB2bOK struct {
	Payload *models.PaymentGatewaySNAPAccessTokenRequest
}

// IsSuccess returns true when this post auth v10 access token b2b o k response has a 2xx status code
func (o *PostAuthV10AccessTokenB2bOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post auth v10 access token b2b o k response has a 3xx status code
func (o *PostAuthV10AccessTokenB2bOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth v10 access token b2b o k response has a 4xx status code
func (o *PostAuthV10AccessTokenB2bOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post auth v10 access token b2b o k response has a 5xx status code
func (o *PostAuthV10AccessTokenB2bOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth v10 access token b2b o k response a status code equal to that given
func (o *PostAuthV10AccessTokenB2bOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post auth v10 access token b2b o k response
func (o *PostAuthV10AccessTokenB2bOK) Code() int {
	return 200
}

func (o *PostAuthV10AccessTokenB2bOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/v1.0/access-token/b2b][%d] postAuthV10AccessTokenB2bOK %s", 200, payload)
}

func (o *PostAuthV10AccessTokenB2bOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/v1.0/access-token/b2b][%d] postAuthV10AccessTokenB2bOK %s", 200, payload)
}

func (o *PostAuthV10AccessTokenB2bOK) GetPayload() *models.PaymentGatewaySNAPAccessTokenRequest {
	return o.Payload
}

func (o *PostAuthV10AccessTokenB2bOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaymentGatewaySNAPAccessTokenRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAuthV10AccessTokenB2bBadRequest creates a PostAuthV10AccessTokenB2bBadRequest with default headers values
func NewPostAuthV10AccessTokenB2bBadRequest() *PostAuthV10AccessTokenB2bBadRequest {
	return &PostAuthV10AccessTokenB2bBadRequest{}
}

/*
PostAuthV10AccessTokenB2bBadRequest describes a response with status code 400, with default header values.

Invalid request parameters
*/
type PostAuthV10AccessTokenB2bBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this post auth v10 access token b2b bad request response has a 2xx status code
func (o *PostAuthV10AccessTokenB2bBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post auth v10 access token b2b bad request response has a 3xx status code
func (o *PostAuthV10AccessTokenB2bBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth v10 access token b2b bad request response has a 4xx status code
func (o *PostAuthV10AccessTokenB2bBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post auth v10 access token b2b bad request response has a 5xx status code
func (o *PostAuthV10AccessTokenB2bBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth v10 access token b2b bad request response a status code equal to that given
func (o *PostAuthV10AccessTokenB2bBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post auth v10 access token b2b bad request response
func (o *PostAuthV10AccessTokenB2bBadRequest) Code() int {
	return 400
}

func (o *PostAuthV10AccessTokenB2bBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/v1.0/access-token/b2b][%d] postAuthV10AccessTokenB2bBadRequest %s", 400, payload)
}

func (o *PostAuthV10AccessTokenB2bBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/v1.0/access-token/b2b][%d] postAuthV10AccessTokenB2bBadRequest %s", 400, payload)
}

func (o *PostAuthV10AccessTokenB2bBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *PostAuthV10AccessTokenB2bBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAuthV10AccessTokenB2bUnauthorized creates a PostAuthV10AccessTokenB2bUnauthorized with default headers values
func NewPostAuthV10AccessTokenB2bUnauthorized() *PostAuthV10AccessTokenB2bUnauthorized {
	return &PostAuthV10AccessTokenB2bUnauthorized{}
}

/*
PostAuthV10AccessTokenB2bUnauthorized describes a response with status code 401, with default header values.

Invalid client key or signature
*/
type PostAuthV10AccessTokenB2bUnauthorized struct {
	Payload interface{}
}

// IsSuccess returns true when this post auth v10 access token b2b unauthorized response has a 2xx status code
func (o *PostAuthV10AccessTokenB2bUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post auth v10 access token b2b unauthorized response has a 3xx status code
func (o *PostAuthV10AccessTokenB2bUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth v10 access token b2b unauthorized response has a 4xx status code
func (o *PostAuthV10AccessTokenB2bUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post auth v10 access token b2b unauthorized response has a 5xx status code
func (o *PostAuthV10AccessTokenB2bUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post auth v10 access token b2b unauthorized response a status code equal to that given
func (o *PostAuthV10AccessTokenB2bUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post auth v10 access token b2b unauthorized response
func (o *PostAuthV10AccessTokenB2bUnauthorized) Code() int {
	return 401
}

func (o *PostAuthV10AccessTokenB2bUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/v1.0/access-token/b2b][%d] postAuthV10AccessTokenB2bUnauthorized %s", 401, payload)
}

func (o *PostAuthV10AccessTokenB2bUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/v1.0/access-token/b2b][%d] postAuthV10AccessTokenB2bUnauthorized %s", 401, payload)
}

func (o *PostAuthV10AccessTokenB2bUnauthorized) GetPayload() interface{} {
	return o.Payload
}

func (o *PostAuthV10AccessTokenB2bUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAuthV10AccessTokenB2bInternalServerError creates a PostAuthV10AccessTokenB2bInternalServerError with default headers values
func NewPostAuthV10AccessTokenB2bInternalServerError() *PostAuthV10AccessTokenB2bInternalServerError {
	return &PostAuthV10AccessTokenB2bInternalServerError{}
}

/*
PostAuthV10AccessTokenB2bInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type PostAuthV10AccessTokenB2bInternalServerError struct {
	Payload interface{}
}

// IsSuccess returns true when this post auth v10 access token b2b internal server error response has a 2xx status code
func (o *PostAuthV10AccessTokenB2bInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post auth v10 access token b2b internal server error response has a 3xx status code
func (o *PostAuthV10AccessTokenB2bInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post auth v10 access token b2b internal server error response has a 4xx status code
func (o *PostAuthV10AccessTokenB2bInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post auth v10 access token b2b internal server error response has a 5xx status code
func (o *PostAuthV10AccessTokenB2bInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post auth v10 access token b2b internal server error response a status code equal to that given
func (o *PostAuthV10AccessTokenB2bInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post auth v10 access token b2b internal server error response
func (o *PostAuthV10AccessTokenB2bInternalServerError) Code() int {
	return 500
}

func (o *PostAuthV10AccessTokenB2bInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/v1.0/access-token/b2b][%d] postAuthV10AccessTokenB2bInternalServerError %s", 500, payload)
}

func (o *PostAuthV10AccessTokenB2bInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth/v1.0/access-token/b2b][%d] postAuthV10AccessTokenB2bInternalServerError %s", 500, payload)
}

func (o *PostAuthV10AccessTokenB2bInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *PostAuthV10AccessTokenB2bInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
