// Code generated by go-swagger; DO NOT EDIT.

package merchants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetV1MerchantParams creates a new GetV1MerchantParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1MerchantParams() *GetV1MerchantParams {
	return &GetV1MerchantParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1MerchantParamsWithTimeout creates a new GetV1MerchantParams object
// with the ability to set a timeout on a request.
func NewGetV1MerchantParamsWithTimeout(timeout time.Duration) *GetV1MerchantParams {
	return &GetV1MerchantParams{
		timeout: timeout,
	}
}

// NewGetV1MerchantParamsWithContext creates a new GetV1MerchantParams object
// with the ability to set a context for a request.
func NewGetV1MerchantParamsWithContext(ctx context.Context) *GetV1MerchantParams {
	return &GetV1MerchantParams{
		Context: ctx,
	}
}

// NewGetV1MerchantParamsWithHTTPClient creates a new GetV1MerchantParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1MerchantParamsWithHTTPClient(client *http.Client) *GetV1MerchantParams {
	return &GetV1MerchantParams{
		HTTPClient: client,
	}
}

/*
GetV1MerchantParams contains all the parameters to send to the API endpoint

	for the get v1 merchant operation.

	Typically these are written to a http.Request.
*/
type GetV1MerchantParams struct {

	/* Authorization.

	   Bearer token
	*/
	Authorization string

	/* Limit.

	   Items per page (default: 10)
	*/
	Limit *int64

	/* Page.

	   Page number (default: 1)
	*/
	Page *int64

	/* Search.

	   Search term for merchant name
	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 merchant params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1MerchantParams) WithDefaults() *GetV1MerchantParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 merchant params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1MerchantParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 merchant params
func (o *GetV1MerchantParams) WithTimeout(timeout time.Duration) *GetV1MerchantParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 merchant params
func (o *GetV1MerchantParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 merchant params
func (o *GetV1MerchantParams) WithContext(ctx context.Context) *GetV1MerchantParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 merchant params
func (o *GetV1MerchantParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 merchant params
func (o *GetV1MerchantParams) WithHTTPClient(client *http.Client) *GetV1MerchantParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 merchant params
func (o *GetV1MerchantParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get v1 merchant params
func (o *GetV1MerchantParams) WithAuthorization(authorization string) *GetV1MerchantParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get v1 merchant params
func (o *GetV1MerchantParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithLimit adds the limit to the get v1 merchant params
func (o *GetV1MerchantParams) WithLimit(limit *int64) *GetV1MerchantParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get v1 merchant params
func (o *GetV1MerchantParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithPage adds the page to the get v1 merchant params
func (o *GetV1MerchantParams) WithPage(page *int64) *GetV1MerchantParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get v1 merchant params
func (o *GetV1MerchantParams) SetPage(page *int64) {
	o.Page = page
}

// WithSearch adds the search to the get v1 merchant params
func (o *GetV1MerchantParams) WithSearch(search *string) *GetV1MerchantParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the get v1 merchant params
func (o *GetV1MerchantParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1MerchantParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.Search != nil {

		// query param search
		var qrSearch string

		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {

			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
