// Code generated by go-swagger; DO NOT EDIT.

package merchants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/automotechnologies/doitpay-go/models"
)

// GetV1MerchantReader is a Reader for the GetV1Merchant structure.
type GetV1MerchantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1MerchantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1MerchantOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetV1MerchantUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetV1MerchantInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/merchant] GetV1Merchant", response, response.Code())
	}
}

// NewGetV1MerchantOK creates a GetV1MerchantOK with default headers values
func NewGetV1MerchantOK() *GetV1MerchantOK {
	return &GetV1MerchantOK{}
}

/*
GetV1MerchantOK describes a response with status code 200, with default header values.

OK
*/
type GetV1MerchantOK struct {
	Payload *models.PaginatedMerchantResponse
}

// IsSuccess returns true when this get v1 merchant o k response has a 2xx status code
func (o *GetV1MerchantOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 merchant o k response has a 3xx status code
func (o *GetV1MerchantOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 merchant o k response has a 4xx status code
func (o *GetV1MerchantOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 merchant o k response has a 5xx status code
func (o *GetV1MerchantOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 merchant o k response a status code equal to that given
func (o *GetV1MerchantOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 merchant o k response
func (o *GetV1MerchantOK) Code() int {
	return 200
}

func (o *GetV1MerchantOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/merchant][%d] getV1MerchantOK %s", 200, payload)
}

func (o *GetV1MerchantOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/merchant][%d] getV1MerchantOK %s", 200, payload)
}

func (o *GetV1MerchantOK) GetPayload() *models.PaginatedMerchantResponse {
	return o.Payload
}

func (o *GetV1MerchantOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaginatedMerchantResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1MerchantUnauthorized creates a GetV1MerchantUnauthorized with default headers values
func NewGetV1MerchantUnauthorized() *GetV1MerchantUnauthorized {
	return &GetV1MerchantUnauthorized{}
}

/*
GetV1MerchantUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetV1MerchantUnauthorized struct {
	Payload map[string]string
}

// IsSuccess returns true when this get v1 merchant unauthorized response has a 2xx status code
func (o *GetV1MerchantUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 merchant unauthorized response has a 3xx status code
func (o *GetV1MerchantUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 merchant unauthorized response has a 4xx status code
func (o *GetV1MerchantUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 merchant unauthorized response has a 5xx status code
func (o *GetV1MerchantUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 merchant unauthorized response a status code equal to that given
func (o *GetV1MerchantUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get v1 merchant unauthorized response
func (o *GetV1MerchantUnauthorized) Code() int {
	return 401
}

func (o *GetV1MerchantUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/merchant][%d] getV1MerchantUnauthorized %s", 401, payload)
}

func (o *GetV1MerchantUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/merchant][%d] getV1MerchantUnauthorized %s", 401, payload)
}

func (o *GetV1MerchantUnauthorized) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetV1MerchantUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1MerchantInternalServerError creates a GetV1MerchantInternalServerError with default headers values
func NewGetV1MerchantInternalServerError() *GetV1MerchantInternalServerError {
	return &GetV1MerchantInternalServerError{}
}

/*
GetV1MerchantInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetV1MerchantInternalServerError struct {
	Payload map[string]string
}

// IsSuccess returns true when this get v1 merchant internal server error response has a 2xx status code
func (o *GetV1MerchantInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 merchant internal server error response has a 3xx status code
func (o *GetV1MerchantInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 merchant internal server error response has a 4xx status code
func (o *GetV1MerchantInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 merchant internal server error response has a 5xx status code
func (o *GetV1MerchantInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get v1 merchant internal server error response a status code equal to that given
func (o *GetV1MerchantInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get v1 merchant internal server error response
func (o *GetV1MerchantInternalServerError) Code() int {
	return 500
}

func (o *GetV1MerchantInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/merchant][%d] getV1MerchantInternalServerError %s", 500, payload)
}

func (o *GetV1MerchantInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/merchant][%d] getV1MerchantInternalServerError %s", 500, payload)
}

func (o *GetV1MerchantInternalServerError) GetPayload() map[string]string {
	return o.Payload
}

func (o *GetV1MerchantInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
