// Code generated by go-swagger; DO NOT EDIT.

package merchants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV10MerchantMerchantRefParams creates a new GetAPIV10MerchantMerchantRefParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV10MerchantMerchantRefParams() *GetAPIV10MerchantMerchantRefParams {
	return &GetAPIV10MerchantMerchantRefParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV10MerchantMerchantRefParamsWithTimeout creates a new GetAPIV10MerchantMerchantRefParams object
// with the ability to set a timeout on a request.
func NewGetAPIV10MerchantMerchantRefParamsWithTimeout(timeout time.Duration) *GetAPIV10MerchantMerchantRefParams {
	return &GetAPIV10MerchantMerchantRefParams{
		timeout: timeout,
	}
}

// NewGetAPIV10MerchantMerchantRefParamsWithContext creates a new GetAPIV10MerchantMerchantRefParams object
// with the ability to set a context for a request.
func NewGetAPIV10MerchantMerchantRefParamsWithContext(ctx context.Context) *GetAPIV10MerchantMerchantRefParams {
	return &GetAPIV10MerchantMerchantRefParams{
		Context: ctx,
	}
}

// NewGetAPIV10MerchantMerchantRefParamsWithHTTPClient creates a new GetAPIV10MerchantMerchantRefParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV10MerchantMerchantRefParamsWithHTTPClient(client *http.Client) *GetAPIV10MerchantMerchantRefParams {
	return &GetAPIV10MerchantMerchantRefParams{
		HTTPClient: client,
	}
}

/*
GetAPIV10MerchantMerchantRefParams contains all the parameters to send to the API endpoint

	for the get API v10 merchant merchant ref operation.

	Typically these are written to a http.Request.
*/
type GetAPIV10MerchantMerchantRefParams struct {

	/* CHANNELID.

	   Channel ID
	*/
	CHANNELID string

	/* XEXTERNALID.

	   External ID
	*/
	XEXTERNALID string

	/* XSIGNATURE.

	   Request signature
	*/
	XSIGNATURE string

	/* XTIMESTAMP.

	   Request timestamp
	*/
	XTIMESTAMP string

	/* MerchantRef.

	   Merchant reference ID
	*/
	MerchantRef string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v10 merchant merchant ref params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV10MerchantMerchantRefParams) WithDefaults() *GetAPIV10MerchantMerchantRefParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v10 merchant merchant ref params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV10MerchantMerchantRefParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v10 merchant merchant ref params
func (o *GetAPIV10MerchantMerchantRefParams) WithTimeout(timeout time.Duration) *GetAPIV10MerchantMerchantRefParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v10 merchant merchant ref params
func (o *GetAPIV10MerchantMerchantRefParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v10 merchant merchant ref params
func (o *GetAPIV10MerchantMerchantRefParams) WithContext(ctx context.Context) *GetAPIV10MerchantMerchantRefParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v10 merchant merchant ref params
func (o *GetAPIV10MerchantMerchantRefParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v10 merchant merchant ref params
func (o *GetAPIV10MerchantMerchantRefParams) WithHTTPClient(client *http.Client) *GetAPIV10MerchantMerchantRefParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v10 merchant merchant ref params
func (o *GetAPIV10MerchantMerchantRefParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCHANNELID adds the cHANNELID to the get API v10 merchant merchant ref params
func (o *GetAPIV10MerchantMerchantRefParams) WithCHANNELID(cHANNELID string) *GetAPIV10MerchantMerchantRefParams {
	o.SetCHANNELID(cHANNELID)
	return o
}

// SetCHANNELID adds the cHANNELId to the get API v10 merchant merchant ref params
func (o *GetAPIV10MerchantMerchantRefParams) SetCHANNELID(cHANNELID string) {
	o.CHANNELID = cHANNELID
}

// WithXEXTERNALID adds the xEXTERNALID to the get API v10 merchant merchant ref params
func (o *GetAPIV10MerchantMerchantRefParams) WithXEXTERNALID(xEXTERNALID string) *GetAPIV10MerchantMerchantRefParams {
	o.SetXEXTERNALID(xEXTERNALID)
	return o
}

// SetXEXTERNALID adds the xEXTERNALId to the get API v10 merchant merchant ref params
func (o *GetAPIV10MerchantMerchantRefParams) SetXEXTERNALID(xEXTERNALID string) {
	o.XEXTERNALID = xEXTERNALID
}

// WithXSIGNATURE adds the xSIGNATURE to the get API v10 merchant merchant ref params
func (o *GetAPIV10MerchantMerchantRefParams) WithXSIGNATURE(xSIGNATURE string) *GetAPIV10MerchantMerchantRefParams {
	o.SetXSIGNATURE(xSIGNATURE)
	return o
}

// SetXSIGNATURE adds the xSIGNATURE to the get API v10 merchant merchant ref params
func (o *GetAPIV10MerchantMerchantRefParams) SetXSIGNATURE(xSIGNATURE string) {
	o.XSIGNATURE = xSIGNATURE
}

// WithXTIMESTAMP adds the xTIMESTAMP to the get API v10 merchant merchant ref params
func (o *GetAPIV10MerchantMerchantRefParams) WithXTIMESTAMP(xTIMESTAMP string) *GetAPIV10MerchantMerchantRefParams {
	o.SetXTIMESTAMP(xTIMESTAMP)
	return o
}

// SetXTIMESTAMP adds the xTIMESTAMP to the get API v10 merchant merchant ref params
func (o *GetAPIV10MerchantMerchantRefParams) SetXTIMESTAMP(xTIMESTAMP string) {
	o.XTIMESTAMP = xTIMESTAMP
}

// WithMerchantRef adds the merchantRef to the get API v10 merchant merchant ref params
func (o *GetAPIV10MerchantMerchantRefParams) WithMerchantRef(merchantRef string) *GetAPIV10MerchantMerchantRefParams {
	o.SetMerchantRef(merchantRef)
	return o
}

// SetMerchantRef adds the merchantRef to the get API v10 merchant merchant ref params
func (o *GetAPIV10MerchantMerchantRefParams) SetMerchantRef(merchantRef string) {
	o.MerchantRef = merchantRef
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV10MerchantMerchantRefParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param CHANNEL-ID
	if err := r.SetHeaderParam("CHANNEL-ID", o.CHANNELID); err != nil {
		return err
	}

	// header param X-EXTERNAL-ID
	if err := r.SetHeaderParam("X-EXTERNAL-ID", o.XEXTERNALID); err != nil {
		return err
	}

	// header param X-SIGNATURE
	if err := r.SetHeaderParam("X-SIGNATURE", o.XSIGNATURE); err != nil {
		return err
	}

	// header param X-TIMESTAMP
	if err := r.SetHeaderParam("X-TIMESTAMP", o.XTIMESTAMP); err != nil {
		return err
	}

	// path param merchant_ref
	if err := r.SetPathParam("merchant_ref", o.MerchantRef); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
