// Code generated by go-swagger; DO NOT EDIT.

package payment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostV10DebitNotifyParams creates a new PostV10DebitNotifyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV10DebitNotifyParams() *PostV10DebitNotifyParams {
	return &PostV10DebitNotifyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV10DebitNotifyParamsWithTimeout creates a new PostV10DebitNotifyParams object
// with the ability to set a timeout on a request.
func NewPostV10DebitNotifyParamsWithTimeout(timeout time.Duration) *PostV10DebitNotifyParams {
	return &PostV10DebitNotifyParams{
		timeout: timeout,
	}
}

// NewPostV10DebitNotifyParamsWithContext creates a new PostV10DebitNotifyParams object
// with the ability to set a context for a request.
func NewPostV10DebitNotifyParamsWithContext(ctx context.Context) *PostV10DebitNotifyParams {
	return &PostV10DebitNotifyParams{
		Context: ctx,
	}
}

// NewPostV10DebitNotifyParamsWithHTTPClient creates a new PostV10DebitNotifyParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV10DebitNotifyParamsWithHTTPClient(client *http.Client) *PostV10DebitNotifyParams {
	return &PostV10DebitNotifyParams{
		HTTPClient: client,
	}
}

/*
PostV10DebitNotifyParams contains all the parameters to send to the API endpoint

	for the post v10 debit notify operation.

	Typically these are written to a http.Request.
*/
type PostV10DebitNotifyParams struct {

	/* Request.

	   E-wallet notification request
	*/
	Request []int64

	/* XPARTNERID.

	   Partner ID
	*/
	XPARTNERID string

	/* XSIGNATURE.

	   Request signature
	*/
	XSIGNATURE string

	/* XTIMESTAMP.

	   Request timestamp
	*/
	XTIMESTAMP string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v10 debit notify params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV10DebitNotifyParams) WithDefaults() *PostV10DebitNotifyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v10 debit notify params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV10DebitNotifyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v10 debit notify params
func (o *PostV10DebitNotifyParams) WithTimeout(timeout time.Duration) *PostV10DebitNotifyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v10 debit notify params
func (o *PostV10DebitNotifyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v10 debit notify params
func (o *PostV10DebitNotifyParams) WithContext(ctx context.Context) *PostV10DebitNotifyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v10 debit notify params
func (o *PostV10DebitNotifyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v10 debit notify params
func (o *PostV10DebitNotifyParams) WithHTTPClient(client *http.Client) *PostV10DebitNotifyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v10 debit notify params
func (o *PostV10DebitNotifyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post v10 debit notify params
func (o *PostV10DebitNotifyParams) WithRequest(request []int64) *PostV10DebitNotifyParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post v10 debit notify params
func (o *PostV10DebitNotifyParams) SetRequest(request []int64) {
	o.Request = request
}

// WithXPARTNERID adds the xPARTNERID to the post v10 debit notify params
func (o *PostV10DebitNotifyParams) WithXPARTNERID(xPARTNERID string) *PostV10DebitNotifyParams {
	o.SetXPARTNERID(xPARTNERID)
	return o
}

// SetXPARTNERID adds the xPARTNERId to the post v10 debit notify params
func (o *PostV10DebitNotifyParams) SetXPARTNERID(xPARTNERID string) {
	o.XPARTNERID = xPARTNERID
}

// WithXSIGNATURE adds the xSIGNATURE to the post v10 debit notify params
func (o *PostV10DebitNotifyParams) WithXSIGNATURE(xSIGNATURE string) *PostV10DebitNotifyParams {
	o.SetXSIGNATURE(xSIGNATURE)
	return o
}

// SetXSIGNATURE adds the xSIGNATURE to the post v10 debit notify params
func (o *PostV10DebitNotifyParams) SetXSIGNATURE(xSIGNATURE string) {
	o.XSIGNATURE = xSIGNATURE
}

// WithXTIMESTAMP adds the xTIMESTAMP to the post v10 debit notify params
func (o *PostV10DebitNotifyParams) WithXTIMESTAMP(xTIMESTAMP string) *PostV10DebitNotifyParams {
	o.SetXTIMESTAMP(xTIMESTAMP)
	return o
}

// SetXTIMESTAMP adds the xTIMESTAMP to the post v10 debit notify params
func (o *PostV10DebitNotifyParams) SetXTIMESTAMP(xTIMESTAMP string) {
	o.XTIMESTAMP = xTIMESTAMP
}

// WriteToRequest writes these params to a swagger request
func (o *PostV10DebitNotifyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// header param X-PARTNER-ID
	if err := r.SetHeaderParam("X-PARTNER-ID", o.XPARTNERID); err != nil {
		return err
	}

	// header param X-SIGNATURE
	if err := r.SetHeaderParam("X-SIGNATURE", o.XSIGNATURE); err != nil {
		return err
	}

	// header param X-TIMESTAMP
	if err := r.SetHeaderParam("X-TIMESTAMP", o.XTIMESTAMP); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
