// Code generated by go-swagger; DO NOT EDIT.

package disbursement

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/automotechnologies/doitpay-go/models"
)

// NewPostDisbursementV10BankDisbursementParams creates a new PostDisbursementV10BankDisbursementParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostDisbursementV10BankDisbursementParams() *PostDisbursementV10BankDisbursementParams {
	return &PostDisbursementV10BankDisbursementParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostDisbursementV10BankDisbursementParamsWithTimeout creates a new PostDisbursementV10BankDisbursementParams object
// with the ability to set a timeout on a request.
func NewPostDisbursementV10BankDisbursementParamsWithTimeout(timeout time.Duration) *PostDisbursementV10BankDisbursementParams {
	return &PostDisbursementV10BankDisbursementParams{
		timeout: timeout,
	}
}

// NewPostDisbursementV10BankDisbursementParamsWithContext creates a new PostDisbursementV10BankDisbursementParams object
// with the ability to set a context for a request.
func NewPostDisbursementV10BankDisbursementParamsWithContext(ctx context.Context) *PostDisbursementV10BankDisbursementParams {
	return &PostDisbursementV10BankDisbursementParams{
		Context: ctx,
	}
}

// NewPostDisbursementV10BankDisbursementParamsWithHTTPClient creates a new PostDisbursementV10BankDisbursementParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostDisbursementV10BankDisbursementParamsWithHTTPClient(client *http.Client) *PostDisbursementV10BankDisbursementParams {
	return &PostDisbursementV10BankDisbursementParams{
		HTTPClient: client,
	}
}

/*
PostDisbursementV10BankDisbursementParams contains all the parameters to send to the API endpoint

	for the post disbursement v10 bank disbursement operation.

	Typically these are written to a http.Request.
*/
type PostDisbursementV10BankDisbursementParams struct {

	/* CHANNELID.

	   Channel ID
	*/
	CHANNELID string

	/* Request.

	   Disbursement request
	*/
	Request *models.CreateDisbursementRequest

	/* XEXTERNALID.

	   External ID
	*/
	XEXTERNALID string

	/* XSIGNATURE.

	   Request signature
	*/
	XSIGNATURE string

	/* XTIMESTAMP.

	   Request timestamp
	*/
	XTIMESTAMP string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post disbursement v10 bank disbursement params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDisbursementV10BankDisbursementParams) WithDefaults() *PostDisbursementV10BankDisbursementParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post disbursement v10 bank disbursement params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDisbursementV10BankDisbursementParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post disbursement v10 bank disbursement params
func (o *PostDisbursementV10BankDisbursementParams) WithTimeout(timeout time.Duration) *PostDisbursementV10BankDisbursementParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post disbursement v10 bank disbursement params
func (o *PostDisbursementV10BankDisbursementParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post disbursement v10 bank disbursement params
func (o *PostDisbursementV10BankDisbursementParams) WithContext(ctx context.Context) *PostDisbursementV10BankDisbursementParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post disbursement v10 bank disbursement params
func (o *PostDisbursementV10BankDisbursementParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post disbursement v10 bank disbursement params
func (o *PostDisbursementV10BankDisbursementParams) WithHTTPClient(client *http.Client) *PostDisbursementV10BankDisbursementParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post disbursement v10 bank disbursement params
func (o *PostDisbursementV10BankDisbursementParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCHANNELID adds the cHANNELID to the post disbursement v10 bank disbursement params
func (o *PostDisbursementV10BankDisbursementParams) WithCHANNELID(cHANNELID string) *PostDisbursementV10BankDisbursementParams {
	o.SetCHANNELID(cHANNELID)
	return o
}

// SetCHANNELID adds the cHANNELId to the post disbursement v10 bank disbursement params
func (o *PostDisbursementV10BankDisbursementParams) SetCHANNELID(cHANNELID string) {
	o.CHANNELID = cHANNELID
}

// WithRequest adds the request to the post disbursement v10 bank disbursement params
func (o *PostDisbursementV10BankDisbursementParams) WithRequest(request *models.CreateDisbursementRequest) *PostDisbursementV10BankDisbursementParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post disbursement v10 bank disbursement params
func (o *PostDisbursementV10BankDisbursementParams) SetRequest(request *models.CreateDisbursementRequest) {
	o.Request = request
}

// WithXEXTERNALID adds the xEXTERNALID to the post disbursement v10 bank disbursement params
func (o *PostDisbursementV10BankDisbursementParams) WithXEXTERNALID(xEXTERNALID string) *PostDisbursementV10BankDisbursementParams {
	o.SetXEXTERNALID(xEXTERNALID)
	return o
}

// SetXEXTERNALID adds the xEXTERNALId to the post disbursement v10 bank disbursement params
func (o *PostDisbursementV10BankDisbursementParams) SetXEXTERNALID(xEXTERNALID string) {
	o.XEXTERNALID = xEXTERNALID
}

// WithXSIGNATURE adds the xSIGNATURE to the post disbursement v10 bank disbursement params
func (o *PostDisbursementV10BankDisbursementParams) WithXSIGNATURE(xSIGNATURE string) *PostDisbursementV10BankDisbursementParams {
	o.SetXSIGNATURE(xSIGNATURE)
	return o
}

// SetXSIGNATURE adds the xSIGNATURE to the post disbursement v10 bank disbursement params
func (o *PostDisbursementV10BankDisbursementParams) SetXSIGNATURE(xSIGNATURE string) {
	o.XSIGNATURE = xSIGNATURE
}

// WithXTIMESTAMP adds the xTIMESTAMP to the post disbursement v10 bank disbursement params
func (o *PostDisbursementV10BankDisbursementParams) WithXTIMESTAMP(xTIMESTAMP string) *PostDisbursementV10BankDisbursementParams {
	o.SetXTIMESTAMP(xTIMESTAMP)
	return o
}

// SetXTIMESTAMP adds the xTIMESTAMP to the post disbursement v10 bank disbursement params
func (o *PostDisbursementV10BankDisbursementParams) SetXTIMESTAMP(xTIMESTAMP string) {
	o.XTIMESTAMP = xTIMESTAMP
}

// WriteToRequest writes these params to a swagger request
func (o *PostDisbursementV10BankDisbursementParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param CHANNEL-ID
	if err := r.SetHeaderParam("CHANNEL-ID", o.CHANNELID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// header param X-EXTERNAL-ID
	if err := r.SetHeaderParam("X-EXTERNAL-ID", o.XEXTERNALID); err != nil {
		return err
	}

	// header param X-SIGNATURE
	if err := r.SetHeaderParam("X-SIGNATURE", o.XSIGNATURE); err != nil {
		return err
	}

	// header param X-TIMESTAMP
	if err := r.SetHeaderParam("X-TIMESTAMP", o.XTIMESTAMP); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
