// Code generated by go-swagger; DO NOT EDIT.

package disbursement

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/automotechnologies/doitpay-go/v2/models"
)

// PostDisbursementV10EmoneyDisbursementReader is a Reader for the PostDisbursementV10EmoneyDisbursement structure.
type PostDisbursementV10EmoneyDisbursementReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDisbursementV10EmoneyDisbursementReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostDisbursementV10EmoneyDisbursementOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostDisbursementV10EmoneyDisbursementBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostDisbursementV10EmoneyDisbursementUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 402:
		result := NewPostDisbursementV10EmoneyDisbursementPaymentRequired()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostDisbursementV10EmoneyDisbursementNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostDisbursementV10EmoneyDisbursementConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostDisbursementV10EmoneyDisbursementInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /disbursement/v1.0/emoney-disbursement] PostDisbursementV10EmoneyDisbursement", response, response.Code())
	}
}

// NewPostDisbursementV10EmoneyDisbursementOK creates a PostDisbursementV10EmoneyDisbursementOK with default headers values
func NewPostDisbursementV10EmoneyDisbursementOK() *PostDisbursementV10EmoneyDisbursementOK {
	return &PostDisbursementV10EmoneyDisbursementOK{}
}

/*
PostDisbursementV10EmoneyDisbursementOK describes a response with status code 200, with default header values.

OK
*/
type PostDisbursementV10EmoneyDisbursementOK struct {
	Payload *models.CreateEwalletTopupResponse
}

// IsSuccess returns true when this post disbursement v10 emoney disbursement o k response has a 2xx status code
func (o *PostDisbursementV10EmoneyDisbursementOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post disbursement v10 emoney disbursement o k response has a 3xx status code
func (o *PostDisbursementV10EmoneyDisbursementOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post disbursement v10 emoney disbursement o k response has a 4xx status code
func (o *PostDisbursementV10EmoneyDisbursementOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post disbursement v10 emoney disbursement o k response has a 5xx status code
func (o *PostDisbursementV10EmoneyDisbursementOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post disbursement v10 emoney disbursement o k response a status code equal to that given
func (o *PostDisbursementV10EmoneyDisbursementOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post disbursement v10 emoney disbursement o k response
func (o *PostDisbursementV10EmoneyDisbursementOK) Code() int {
	return 200
}

func (o *PostDisbursementV10EmoneyDisbursementOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-disbursement][%d] postDisbursementV10EmoneyDisbursementOK %s", 200, payload)
}

func (o *PostDisbursementV10EmoneyDisbursementOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-disbursement][%d] postDisbursementV10EmoneyDisbursementOK %s", 200, payload)
}

func (o *PostDisbursementV10EmoneyDisbursementOK) GetPayload() *models.CreateEwalletTopupResponse {
	return o.Payload
}

func (o *PostDisbursementV10EmoneyDisbursementOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateEwalletTopupResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDisbursementV10EmoneyDisbursementBadRequest creates a PostDisbursementV10EmoneyDisbursementBadRequest with default headers values
func NewPostDisbursementV10EmoneyDisbursementBadRequest() *PostDisbursementV10EmoneyDisbursementBadRequest {
	return &PostDisbursementV10EmoneyDisbursementBadRequest{}
}

/*
PostDisbursementV10EmoneyDisbursementBadRequest describes a response with status code 400, with default header values.

Invalid request parameters
*/
type PostDisbursementV10EmoneyDisbursementBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this post disbursement v10 emoney disbursement bad request response has a 2xx status code
func (o *PostDisbursementV10EmoneyDisbursementBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post disbursement v10 emoney disbursement bad request response has a 3xx status code
func (o *PostDisbursementV10EmoneyDisbursementBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post disbursement v10 emoney disbursement bad request response has a 4xx status code
func (o *PostDisbursementV10EmoneyDisbursementBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post disbursement v10 emoney disbursement bad request response has a 5xx status code
func (o *PostDisbursementV10EmoneyDisbursementBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post disbursement v10 emoney disbursement bad request response a status code equal to that given
func (o *PostDisbursementV10EmoneyDisbursementBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post disbursement v10 emoney disbursement bad request response
func (o *PostDisbursementV10EmoneyDisbursementBadRequest) Code() int {
	return 400
}

func (o *PostDisbursementV10EmoneyDisbursementBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-disbursement][%d] postDisbursementV10EmoneyDisbursementBadRequest %s", 400, payload)
}

func (o *PostDisbursementV10EmoneyDisbursementBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-disbursement][%d] postDisbursementV10EmoneyDisbursementBadRequest %s", 400, payload)
}

func (o *PostDisbursementV10EmoneyDisbursementBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *PostDisbursementV10EmoneyDisbursementBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDisbursementV10EmoneyDisbursementUnauthorized creates a PostDisbursementV10EmoneyDisbursementUnauthorized with default headers values
func NewPostDisbursementV10EmoneyDisbursementUnauthorized() *PostDisbursementV10EmoneyDisbursementUnauthorized {
	return &PostDisbursementV10EmoneyDisbursementUnauthorized{}
}

/*
PostDisbursementV10EmoneyDisbursementUnauthorized describes a response with status code 401, with default header values.

Authentication failed
*/
type PostDisbursementV10EmoneyDisbursementUnauthorized struct {
	Payload interface{}
}

// IsSuccess returns true when this post disbursement v10 emoney disbursement unauthorized response has a 2xx status code
func (o *PostDisbursementV10EmoneyDisbursementUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post disbursement v10 emoney disbursement unauthorized response has a 3xx status code
func (o *PostDisbursementV10EmoneyDisbursementUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post disbursement v10 emoney disbursement unauthorized response has a 4xx status code
func (o *PostDisbursementV10EmoneyDisbursementUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post disbursement v10 emoney disbursement unauthorized response has a 5xx status code
func (o *PostDisbursementV10EmoneyDisbursementUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post disbursement v10 emoney disbursement unauthorized response a status code equal to that given
func (o *PostDisbursementV10EmoneyDisbursementUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post disbursement v10 emoney disbursement unauthorized response
func (o *PostDisbursementV10EmoneyDisbursementUnauthorized) Code() int {
	return 401
}

func (o *PostDisbursementV10EmoneyDisbursementUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-disbursement][%d] postDisbursementV10EmoneyDisbursementUnauthorized %s", 401, payload)
}

func (o *PostDisbursementV10EmoneyDisbursementUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-disbursement][%d] postDisbursementV10EmoneyDisbursementUnauthorized %s", 401, payload)
}

func (o *PostDisbursementV10EmoneyDisbursementUnauthorized) GetPayload() interface{} {
	return o.Payload
}

func (o *PostDisbursementV10EmoneyDisbursementUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDisbursementV10EmoneyDisbursementPaymentRequired creates a PostDisbursementV10EmoneyDisbursementPaymentRequired with default headers values
func NewPostDisbursementV10EmoneyDisbursementPaymentRequired() *PostDisbursementV10EmoneyDisbursementPaymentRequired {
	return &PostDisbursementV10EmoneyDisbursementPaymentRequired{}
}

/*
PostDisbursementV10EmoneyDisbursementPaymentRequired describes a response with status code 402, with default header values.

Insufficient balance
*/
type PostDisbursementV10EmoneyDisbursementPaymentRequired struct {
	Payload interface{}
}

// IsSuccess returns true when this post disbursement v10 emoney disbursement payment required response has a 2xx status code
func (o *PostDisbursementV10EmoneyDisbursementPaymentRequired) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post disbursement v10 emoney disbursement payment required response has a 3xx status code
func (o *PostDisbursementV10EmoneyDisbursementPaymentRequired) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post disbursement v10 emoney disbursement payment required response has a 4xx status code
func (o *PostDisbursementV10EmoneyDisbursementPaymentRequired) IsClientError() bool {
	return true
}

// IsServerError returns true when this post disbursement v10 emoney disbursement payment required response has a 5xx status code
func (o *PostDisbursementV10EmoneyDisbursementPaymentRequired) IsServerError() bool {
	return false
}

// IsCode returns true when this post disbursement v10 emoney disbursement payment required response a status code equal to that given
func (o *PostDisbursementV10EmoneyDisbursementPaymentRequired) IsCode(code int) bool {
	return code == 402
}

// Code gets the status code for the post disbursement v10 emoney disbursement payment required response
func (o *PostDisbursementV10EmoneyDisbursementPaymentRequired) Code() int {
	return 402
}

func (o *PostDisbursementV10EmoneyDisbursementPaymentRequired) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-disbursement][%d] postDisbursementV10EmoneyDisbursementPaymentRequired %s", 402, payload)
}

func (o *PostDisbursementV10EmoneyDisbursementPaymentRequired) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-disbursement][%d] postDisbursementV10EmoneyDisbursementPaymentRequired %s", 402, payload)
}

func (o *PostDisbursementV10EmoneyDisbursementPaymentRequired) GetPayload() interface{} {
	return o.Payload
}

func (o *PostDisbursementV10EmoneyDisbursementPaymentRequired) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDisbursementV10EmoneyDisbursementNotFound creates a PostDisbursementV10EmoneyDisbursementNotFound with default headers values
func NewPostDisbursementV10EmoneyDisbursementNotFound() *PostDisbursementV10EmoneyDisbursementNotFound {
	return &PostDisbursementV10EmoneyDisbursementNotFound{}
}

/*
PostDisbursementV10EmoneyDisbursementNotFound describes a response with status code 404, with default header values.

Account not found
*/
type PostDisbursementV10EmoneyDisbursementNotFound struct {
	Payload interface{}
}

// IsSuccess returns true when this post disbursement v10 emoney disbursement not found response has a 2xx status code
func (o *PostDisbursementV10EmoneyDisbursementNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post disbursement v10 emoney disbursement not found response has a 3xx status code
func (o *PostDisbursementV10EmoneyDisbursementNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post disbursement v10 emoney disbursement not found response has a 4xx status code
func (o *PostDisbursementV10EmoneyDisbursementNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post disbursement v10 emoney disbursement not found response has a 5xx status code
func (o *PostDisbursementV10EmoneyDisbursementNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post disbursement v10 emoney disbursement not found response a status code equal to that given
func (o *PostDisbursementV10EmoneyDisbursementNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the post disbursement v10 emoney disbursement not found response
func (o *PostDisbursementV10EmoneyDisbursementNotFound) Code() int {
	return 404
}

func (o *PostDisbursementV10EmoneyDisbursementNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-disbursement][%d] postDisbursementV10EmoneyDisbursementNotFound %s", 404, payload)
}

func (o *PostDisbursementV10EmoneyDisbursementNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-disbursement][%d] postDisbursementV10EmoneyDisbursementNotFound %s", 404, payload)
}

func (o *PostDisbursementV10EmoneyDisbursementNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *PostDisbursementV10EmoneyDisbursementNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDisbursementV10EmoneyDisbursementConflict creates a PostDisbursementV10EmoneyDisbursementConflict with default headers values
func NewPostDisbursementV10EmoneyDisbursementConflict() *PostDisbursementV10EmoneyDisbursementConflict {
	return &PostDisbursementV10EmoneyDisbursementConflict{}
}

/*
PostDisbursementV10EmoneyDisbursementConflict describes a response with status code 409, with default header values.

Disbursement already exists
*/
type PostDisbursementV10EmoneyDisbursementConflict struct {
	Payload interface{}
}

// IsSuccess returns true when this post disbursement v10 emoney disbursement conflict response has a 2xx status code
func (o *PostDisbursementV10EmoneyDisbursementConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post disbursement v10 emoney disbursement conflict response has a 3xx status code
func (o *PostDisbursementV10EmoneyDisbursementConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post disbursement v10 emoney disbursement conflict response has a 4xx status code
func (o *PostDisbursementV10EmoneyDisbursementConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this post disbursement v10 emoney disbursement conflict response has a 5xx status code
func (o *PostDisbursementV10EmoneyDisbursementConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this post disbursement v10 emoney disbursement conflict response a status code equal to that given
func (o *PostDisbursementV10EmoneyDisbursementConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the post disbursement v10 emoney disbursement conflict response
func (o *PostDisbursementV10EmoneyDisbursementConflict) Code() int {
	return 409
}

func (o *PostDisbursementV10EmoneyDisbursementConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-disbursement][%d] postDisbursementV10EmoneyDisbursementConflict %s", 409, payload)
}

func (o *PostDisbursementV10EmoneyDisbursementConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-disbursement][%d] postDisbursementV10EmoneyDisbursementConflict %s", 409, payload)
}

func (o *PostDisbursementV10EmoneyDisbursementConflict) GetPayload() interface{} {
	return o.Payload
}

func (o *PostDisbursementV10EmoneyDisbursementConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDisbursementV10EmoneyDisbursementInternalServerError creates a PostDisbursementV10EmoneyDisbursementInternalServerError with default headers values
func NewPostDisbursementV10EmoneyDisbursementInternalServerError() *PostDisbursementV10EmoneyDisbursementInternalServerError {
	return &PostDisbursementV10EmoneyDisbursementInternalServerError{}
}

/*
PostDisbursementV10EmoneyDisbursementInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type PostDisbursementV10EmoneyDisbursementInternalServerError struct {
	Payload interface{}
}

// IsSuccess returns true when this post disbursement v10 emoney disbursement internal server error response has a 2xx status code
func (o *PostDisbursementV10EmoneyDisbursementInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post disbursement v10 emoney disbursement internal server error response has a 3xx status code
func (o *PostDisbursementV10EmoneyDisbursementInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post disbursement v10 emoney disbursement internal server error response has a 4xx status code
func (o *PostDisbursementV10EmoneyDisbursementInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post disbursement v10 emoney disbursement internal server error response has a 5xx status code
func (o *PostDisbursementV10EmoneyDisbursementInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post disbursement v10 emoney disbursement internal server error response a status code equal to that given
func (o *PostDisbursementV10EmoneyDisbursementInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post disbursement v10 emoney disbursement internal server error response
func (o *PostDisbursementV10EmoneyDisbursementInternalServerError) Code() int {
	return 500
}

func (o *PostDisbursementV10EmoneyDisbursementInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-disbursement][%d] postDisbursementV10EmoneyDisbursementInternalServerError %s", 500, payload)
}

func (o *PostDisbursementV10EmoneyDisbursementInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-disbursement][%d] postDisbursementV10EmoneyDisbursementInternalServerError %s", 500, payload)
}

func (o *PostDisbursementV10EmoneyDisbursementInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *PostDisbursementV10EmoneyDisbursementInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
