// Code generated by go-swagger; DO NOT EDIT.

package disbursement

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/automotechnologies/doitpay-go/v2/models"
)

// PostDisbursementV10EmoneyAccountValidationReader is a Reader for the PostDisbursementV10EmoneyAccountValidation structure.
type PostDisbursementV10EmoneyAccountValidationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDisbursementV10EmoneyAccountValidationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostDisbursementV10EmoneyAccountValidationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostDisbursementV10EmoneyAccountValidationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostDisbursementV10EmoneyAccountValidationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostDisbursementV10EmoneyAccountValidationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostDisbursementV10EmoneyAccountValidationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /disbursement/v1.0/emoney-account-validation] PostDisbursementV10EmoneyAccountValidation", response, response.Code())
	}
}

// NewPostDisbursementV10EmoneyAccountValidationOK creates a PostDisbursementV10EmoneyAccountValidationOK with default headers values
func NewPostDisbursementV10EmoneyAccountValidationOK() *PostDisbursementV10EmoneyAccountValidationOK {
	return &PostDisbursementV10EmoneyAccountValidationOK{}
}

/*
PostDisbursementV10EmoneyAccountValidationOK describes a response with status code 200, with default header values.

OK
*/
type PostDisbursementV10EmoneyAccountValidationOK struct {
	Payload *models.EmoneyAccountValidationResponse
}

// IsSuccess returns true when this post disbursement v10 emoney account validation o k response has a 2xx status code
func (o *PostDisbursementV10EmoneyAccountValidationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post disbursement v10 emoney account validation o k response has a 3xx status code
func (o *PostDisbursementV10EmoneyAccountValidationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post disbursement v10 emoney account validation o k response has a 4xx status code
func (o *PostDisbursementV10EmoneyAccountValidationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post disbursement v10 emoney account validation o k response has a 5xx status code
func (o *PostDisbursementV10EmoneyAccountValidationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post disbursement v10 emoney account validation o k response a status code equal to that given
func (o *PostDisbursementV10EmoneyAccountValidationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post disbursement v10 emoney account validation o k response
func (o *PostDisbursementV10EmoneyAccountValidationOK) Code() int {
	return 200
}

func (o *PostDisbursementV10EmoneyAccountValidationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-account-validation][%d] postDisbursementV10EmoneyAccountValidationOK %s", 200, payload)
}

func (o *PostDisbursementV10EmoneyAccountValidationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-account-validation][%d] postDisbursementV10EmoneyAccountValidationOK %s", 200, payload)
}

func (o *PostDisbursementV10EmoneyAccountValidationOK) GetPayload() *models.EmoneyAccountValidationResponse {
	return o.Payload
}

func (o *PostDisbursementV10EmoneyAccountValidationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EmoneyAccountValidationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDisbursementV10EmoneyAccountValidationBadRequest creates a PostDisbursementV10EmoneyAccountValidationBadRequest with default headers values
func NewPostDisbursementV10EmoneyAccountValidationBadRequest() *PostDisbursementV10EmoneyAccountValidationBadRequest {
	return &PostDisbursementV10EmoneyAccountValidationBadRequest{}
}

/*
PostDisbursementV10EmoneyAccountValidationBadRequest describes a response with status code 400, with default header values.

Invalid request parameters
*/
type PostDisbursementV10EmoneyAccountValidationBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this post disbursement v10 emoney account validation bad request response has a 2xx status code
func (o *PostDisbursementV10EmoneyAccountValidationBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post disbursement v10 emoney account validation bad request response has a 3xx status code
func (o *PostDisbursementV10EmoneyAccountValidationBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post disbursement v10 emoney account validation bad request response has a 4xx status code
func (o *PostDisbursementV10EmoneyAccountValidationBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post disbursement v10 emoney account validation bad request response has a 5xx status code
func (o *PostDisbursementV10EmoneyAccountValidationBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post disbursement v10 emoney account validation bad request response a status code equal to that given
func (o *PostDisbursementV10EmoneyAccountValidationBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post disbursement v10 emoney account validation bad request response
func (o *PostDisbursementV10EmoneyAccountValidationBadRequest) Code() int {
	return 400
}

func (o *PostDisbursementV10EmoneyAccountValidationBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-account-validation][%d] postDisbursementV10EmoneyAccountValidationBadRequest %s", 400, payload)
}

func (o *PostDisbursementV10EmoneyAccountValidationBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-account-validation][%d] postDisbursementV10EmoneyAccountValidationBadRequest %s", 400, payload)
}

func (o *PostDisbursementV10EmoneyAccountValidationBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *PostDisbursementV10EmoneyAccountValidationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDisbursementV10EmoneyAccountValidationUnauthorized creates a PostDisbursementV10EmoneyAccountValidationUnauthorized with default headers values
func NewPostDisbursementV10EmoneyAccountValidationUnauthorized() *PostDisbursementV10EmoneyAccountValidationUnauthorized {
	return &PostDisbursementV10EmoneyAccountValidationUnauthorized{}
}

/*
PostDisbursementV10EmoneyAccountValidationUnauthorized describes a response with status code 401, with default header values.

Authentication failed
*/
type PostDisbursementV10EmoneyAccountValidationUnauthorized struct {
	Payload interface{}
}

// IsSuccess returns true when this post disbursement v10 emoney account validation unauthorized response has a 2xx status code
func (o *PostDisbursementV10EmoneyAccountValidationUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post disbursement v10 emoney account validation unauthorized response has a 3xx status code
func (o *PostDisbursementV10EmoneyAccountValidationUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post disbursement v10 emoney account validation unauthorized response has a 4xx status code
func (o *PostDisbursementV10EmoneyAccountValidationUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post disbursement v10 emoney account validation unauthorized response has a 5xx status code
func (o *PostDisbursementV10EmoneyAccountValidationUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post disbursement v10 emoney account validation unauthorized response a status code equal to that given
func (o *PostDisbursementV10EmoneyAccountValidationUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post disbursement v10 emoney account validation unauthorized response
func (o *PostDisbursementV10EmoneyAccountValidationUnauthorized) Code() int {
	return 401
}

func (o *PostDisbursementV10EmoneyAccountValidationUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-account-validation][%d] postDisbursementV10EmoneyAccountValidationUnauthorized %s", 401, payload)
}

func (o *PostDisbursementV10EmoneyAccountValidationUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-account-validation][%d] postDisbursementV10EmoneyAccountValidationUnauthorized %s", 401, payload)
}

func (o *PostDisbursementV10EmoneyAccountValidationUnauthorized) GetPayload() interface{} {
	return o.Payload
}

func (o *PostDisbursementV10EmoneyAccountValidationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDisbursementV10EmoneyAccountValidationNotFound creates a PostDisbursementV10EmoneyAccountValidationNotFound with default headers values
func NewPostDisbursementV10EmoneyAccountValidationNotFound() *PostDisbursementV10EmoneyAccountValidationNotFound {
	return &PostDisbursementV10EmoneyAccountValidationNotFound{}
}

/*
PostDisbursementV10EmoneyAccountValidationNotFound describes a response with status code 404, with default header values.

Account not found
*/
type PostDisbursementV10EmoneyAccountValidationNotFound struct {
	Payload interface{}
}

// IsSuccess returns true when this post disbursement v10 emoney account validation not found response has a 2xx status code
func (o *PostDisbursementV10EmoneyAccountValidationNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post disbursement v10 emoney account validation not found response has a 3xx status code
func (o *PostDisbursementV10EmoneyAccountValidationNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post disbursement v10 emoney account validation not found response has a 4xx status code
func (o *PostDisbursementV10EmoneyAccountValidationNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post disbursement v10 emoney account validation not found response has a 5xx status code
func (o *PostDisbursementV10EmoneyAccountValidationNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post disbursement v10 emoney account validation not found response a status code equal to that given
func (o *PostDisbursementV10EmoneyAccountValidationNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the post disbursement v10 emoney account validation not found response
func (o *PostDisbursementV10EmoneyAccountValidationNotFound) Code() int {
	return 404
}

func (o *PostDisbursementV10EmoneyAccountValidationNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-account-validation][%d] postDisbursementV10EmoneyAccountValidationNotFound %s", 404, payload)
}

func (o *PostDisbursementV10EmoneyAccountValidationNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-account-validation][%d] postDisbursementV10EmoneyAccountValidationNotFound %s", 404, payload)
}

func (o *PostDisbursementV10EmoneyAccountValidationNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *PostDisbursementV10EmoneyAccountValidationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDisbursementV10EmoneyAccountValidationInternalServerError creates a PostDisbursementV10EmoneyAccountValidationInternalServerError with default headers values
func NewPostDisbursementV10EmoneyAccountValidationInternalServerError() *PostDisbursementV10EmoneyAccountValidationInternalServerError {
	return &PostDisbursementV10EmoneyAccountValidationInternalServerError{}
}

/*
PostDisbursementV10EmoneyAccountValidationInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type PostDisbursementV10EmoneyAccountValidationInternalServerError struct {
	Payload interface{}
}

// IsSuccess returns true when this post disbursement v10 emoney account validation internal server error response has a 2xx status code
func (o *PostDisbursementV10EmoneyAccountValidationInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post disbursement v10 emoney account validation internal server error response has a 3xx status code
func (o *PostDisbursementV10EmoneyAccountValidationInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post disbursement v10 emoney account validation internal server error response has a 4xx status code
func (o *PostDisbursementV10EmoneyAccountValidationInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post disbursement v10 emoney account validation internal server error response has a 5xx status code
func (o *PostDisbursementV10EmoneyAccountValidationInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post disbursement v10 emoney account validation internal server error response a status code equal to that given
func (o *PostDisbursementV10EmoneyAccountValidationInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post disbursement v10 emoney account validation internal server error response
func (o *PostDisbursementV10EmoneyAccountValidationInternalServerError) Code() int {
	return 500
}

func (o *PostDisbursementV10EmoneyAccountValidationInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-account-validation][%d] postDisbursementV10EmoneyAccountValidationInternalServerError %s", 500, payload)
}

func (o *PostDisbursementV10EmoneyAccountValidationInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/emoney-account-validation][%d] postDisbursementV10EmoneyAccountValidationInternalServerError %s", 500, payload)
}

func (o *PostDisbursementV10EmoneyAccountValidationInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *PostDisbursementV10EmoneyAccountValidationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
