// Code generated by go-swagger; DO NOT EDIT.

package disbursement

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/automotechnologies/doitpay-go/v2/models"
)

// PostDisbursementV10BalanceReader is a Reader for the PostDisbursementV10Balance structure.
type PostDisbursementV10BalanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDisbursementV10BalanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostDisbursementV10BalanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostDisbursementV10BalanceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostDisbursementV10BalanceUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostDisbursementV10BalanceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostDisbursementV10BalanceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /disbursement/v1.0/balance] PostDisbursementV10Balance", response, response.Code())
	}
}

// NewPostDisbursementV10BalanceOK creates a PostDisbursementV10BalanceOK with default headers values
func NewPostDisbursementV10BalanceOK() *PostDisbursementV10BalanceOK {
	return &PostDisbursementV10BalanceOK{}
}

/*
PostDisbursementV10BalanceOK describes a response with status code 200, with default header values.

OK
*/
type PostDisbursementV10BalanceOK struct {
	Payload *models.InquiryBalanceResponse
}

// IsSuccess returns true when this post disbursement v10 balance o k response has a 2xx status code
func (o *PostDisbursementV10BalanceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post disbursement v10 balance o k response has a 3xx status code
func (o *PostDisbursementV10BalanceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post disbursement v10 balance o k response has a 4xx status code
func (o *PostDisbursementV10BalanceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post disbursement v10 balance o k response has a 5xx status code
func (o *PostDisbursementV10BalanceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post disbursement v10 balance o k response a status code equal to that given
func (o *PostDisbursementV10BalanceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post disbursement v10 balance o k response
func (o *PostDisbursementV10BalanceOK) Code() int {
	return 200
}

func (o *PostDisbursementV10BalanceOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/balance][%d] postDisbursementV10BalanceOK %s", 200, payload)
}

func (o *PostDisbursementV10BalanceOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/balance][%d] postDisbursementV10BalanceOK %s", 200, payload)
}

func (o *PostDisbursementV10BalanceOK) GetPayload() *models.InquiryBalanceResponse {
	return o.Payload
}

func (o *PostDisbursementV10BalanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InquiryBalanceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDisbursementV10BalanceBadRequest creates a PostDisbursementV10BalanceBadRequest with default headers values
func NewPostDisbursementV10BalanceBadRequest() *PostDisbursementV10BalanceBadRequest {
	return &PostDisbursementV10BalanceBadRequest{}
}

/*
PostDisbursementV10BalanceBadRequest describes a response with status code 400, with default header values.

Invalid request parameters
*/
type PostDisbursementV10BalanceBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this post disbursement v10 balance bad request response has a 2xx status code
func (o *PostDisbursementV10BalanceBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post disbursement v10 balance bad request response has a 3xx status code
func (o *PostDisbursementV10BalanceBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post disbursement v10 balance bad request response has a 4xx status code
func (o *PostDisbursementV10BalanceBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post disbursement v10 balance bad request response has a 5xx status code
func (o *PostDisbursementV10BalanceBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post disbursement v10 balance bad request response a status code equal to that given
func (o *PostDisbursementV10BalanceBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post disbursement v10 balance bad request response
func (o *PostDisbursementV10BalanceBadRequest) Code() int {
	return 400
}

func (o *PostDisbursementV10BalanceBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/balance][%d] postDisbursementV10BalanceBadRequest %s", 400, payload)
}

func (o *PostDisbursementV10BalanceBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/balance][%d] postDisbursementV10BalanceBadRequest %s", 400, payload)
}

func (o *PostDisbursementV10BalanceBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *PostDisbursementV10BalanceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDisbursementV10BalanceUnauthorized creates a PostDisbursementV10BalanceUnauthorized with default headers values
func NewPostDisbursementV10BalanceUnauthorized() *PostDisbursementV10BalanceUnauthorized {
	return &PostDisbursementV10BalanceUnauthorized{}
}

/*
PostDisbursementV10BalanceUnauthorized describes a response with status code 401, with default header values.

Authentication failed
*/
type PostDisbursementV10BalanceUnauthorized struct {
	Payload interface{}
}

// IsSuccess returns true when this post disbursement v10 balance unauthorized response has a 2xx status code
func (o *PostDisbursementV10BalanceUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post disbursement v10 balance unauthorized response has a 3xx status code
func (o *PostDisbursementV10BalanceUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post disbursement v10 balance unauthorized response has a 4xx status code
func (o *PostDisbursementV10BalanceUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post disbursement v10 balance unauthorized response has a 5xx status code
func (o *PostDisbursementV10BalanceUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post disbursement v10 balance unauthorized response a status code equal to that given
func (o *PostDisbursementV10BalanceUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post disbursement v10 balance unauthorized response
func (o *PostDisbursementV10BalanceUnauthorized) Code() int {
	return 401
}

func (o *PostDisbursementV10BalanceUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/balance][%d] postDisbursementV10BalanceUnauthorized %s", 401, payload)
}

func (o *PostDisbursementV10BalanceUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/balance][%d] postDisbursementV10BalanceUnauthorized %s", 401, payload)
}

func (o *PostDisbursementV10BalanceUnauthorized) GetPayload() interface{} {
	return o.Payload
}

func (o *PostDisbursementV10BalanceUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDisbursementV10BalanceNotFound creates a PostDisbursementV10BalanceNotFound with default headers values
func NewPostDisbursementV10BalanceNotFound() *PostDisbursementV10BalanceNotFound {
	return &PostDisbursementV10BalanceNotFound{}
}

/*
PostDisbursementV10BalanceNotFound describes a response with status code 404, with default header values.

Balance not found
*/
type PostDisbursementV10BalanceNotFound struct {
	Payload interface{}
}

// IsSuccess returns true when this post disbursement v10 balance not found response has a 2xx status code
func (o *PostDisbursementV10BalanceNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post disbursement v10 balance not found response has a 3xx status code
func (o *PostDisbursementV10BalanceNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post disbursement v10 balance not found response has a 4xx status code
func (o *PostDisbursementV10BalanceNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post disbursement v10 balance not found response has a 5xx status code
func (o *PostDisbursementV10BalanceNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post disbursement v10 balance not found response a status code equal to that given
func (o *PostDisbursementV10BalanceNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the post disbursement v10 balance not found response
func (o *PostDisbursementV10BalanceNotFound) Code() int {
	return 404
}

func (o *PostDisbursementV10BalanceNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/balance][%d] postDisbursementV10BalanceNotFound %s", 404, payload)
}

func (o *PostDisbursementV10BalanceNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/balance][%d] postDisbursementV10BalanceNotFound %s", 404, payload)
}

func (o *PostDisbursementV10BalanceNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *PostDisbursementV10BalanceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDisbursementV10BalanceInternalServerError creates a PostDisbursementV10BalanceInternalServerError with default headers values
func NewPostDisbursementV10BalanceInternalServerError() *PostDisbursementV10BalanceInternalServerError {
	return &PostDisbursementV10BalanceInternalServerError{}
}

/*
PostDisbursementV10BalanceInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type PostDisbursementV10BalanceInternalServerError struct {
	Payload interface{}
}

// IsSuccess returns true when this post disbursement v10 balance internal server error response has a 2xx status code
func (o *PostDisbursementV10BalanceInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post disbursement v10 balance internal server error response has a 3xx status code
func (o *PostDisbursementV10BalanceInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post disbursement v10 balance internal server error response has a 4xx status code
func (o *PostDisbursementV10BalanceInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post disbursement v10 balance internal server error response has a 5xx status code
func (o *PostDisbursementV10BalanceInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post disbursement v10 balance internal server error response a status code equal to that given
func (o *PostDisbursementV10BalanceInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post disbursement v10 balance internal server error response
func (o *PostDisbursementV10BalanceInternalServerError) Code() int {
	return 500
}

func (o *PostDisbursementV10BalanceInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/balance][%d] postDisbursementV10BalanceInternalServerError %s", 500, payload)
}

func (o *PostDisbursementV10BalanceInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /disbursement/v1.0/balance][%d] postDisbursementV10BalanceInternalServerError %s", 500, payload)
}

func (o *PostDisbursementV10BalanceInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *PostDisbursementV10BalanceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
