// Code generated by go-swagger; DO NOT EDIT.

package disbursement

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/automotechnologies/doitpay-go/v2/models"
)

// NewPostDisbursementV10BankAccountValidationParams creates a new PostDisbursementV10BankAccountValidationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostDisbursementV10BankAccountValidationParams() *PostDisbursementV10BankAccountValidationParams {
	return &PostDisbursementV10BankAccountValidationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostDisbursementV10BankAccountValidationParamsWithTimeout creates a new PostDisbursementV10BankAccountValidationParams object
// with the ability to set a timeout on a request.
func NewPostDisbursementV10BankAccountValidationParamsWithTimeout(timeout time.Duration) *PostDisbursementV10BankAccountValidationParams {
	return &PostDisbursementV10BankAccountValidationParams{
		timeout: timeout,
	}
}

// NewPostDisbursementV10BankAccountValidationParamsWithContext creates a new PostDisbursementV10BankAccountValidationParams object
// with the ability to set a context for a request.
func NewPostDisbursementV10BankAccountValidationParamsWithContext(ctx context.Context) *PostDisbursementV10BankAccountValidationParams {
	return &PostDisbursementV10BankAccountValidationParams{
		Context: ctx,
	}
}

// NewPostDisbursementV10BankAccountValidationParamsWithHTTPClient creates a new PostDisbursementV10BankAccountValidationParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostDisbursementV10BankAccountValidationParamsWithHTTPClient(client *http.Client) *PostDisbursementV10BankAccountValidationParams {
	return &PostDisbursementV10BankAccountValidationParams{
		HTTPClient: client,
	}
}

/*
PostDisbursementV10BankAccountValidationParams contains all the parameters to send to the API endpoint

	for the post disbursement v10 bank account validation operation.

	Typically these are written to a http.Request.
*/
type PostDisbursementV10BankAccountValidationParams struct {

	/* Request.

	   Bank account validation request
	*/
	Request *models.BankAccountValidationRequest

	/* XCLIENTKEY.

	   Client Key
	*/
	XCLIENTKEY string

	/* XSIGNATURE.

	   Request signature
	*/
	XSIGNATURE string

	/* XTIMESTAMP.

	   Request timestamp
	*/
	XTIMESTAMP string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post disbursement v10 bank account validation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDisbursementV10BankAccountValidationParams) WithDefaults() *PostDisbursementV10BankAccountValidationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post disbursement v10 bank account validation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDisbursementV10BankAccountValidationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post disbursement v10 bank account validation params
func (o *PostDisbursementV10BankAccountValidationParams) WithTimeout(timeout time.Duration) *PostDisbursementV10BankAccountValidationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post disbursement v10 bank account validation params
func (o *PostDisbursementV10BankAccountValidationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post disbursement v10 bank account validation params
func (o *PostDisbursementV10BankAccountValidationParams) WithContext(ctx context.Context) *PostDisbursementV10BankAccountValidationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post disbursement v10 bank account validation params
func (o *PostDisbursementV10BankAccountValidationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post disbursement v10 bank account validation params
func (o *PostDisbursementV10BankAccountValidationParams) WithHTTPClient(client *http.Client) *PostDisbursementV10BankAccountValidationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post disbursement v10 bank account validation params
func (o *PostDisbursementV10BankAccountValidationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post disbursement v10 bank account validation params
func (o *PostDisbursementV10BankAccountValidationParams) WithRequest(request *models.BankAccountValidationRequest) *PostDisbursementV10BankAccountValidationParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post disbursement v10 bank account validation params
func (o *PostDisbursementV10BankAccountValidationParams) SetRequest(request *models.BankAccountValidationRequest) {
	o.Request = request
}

// WithXCLIENTKEY adds the xCLIENTKEY to the post disbursement v10 bank account validation params
func (o *PostDisbursementV10BankAccountValidationParams) WithXCLIENTKEY(xCLIENTKEY string) *PostDisbursementV10BankAccountValidationParams {
	o.SetXCLIENTKEY(xCLIENTKEY)
	return o
}

// SetXCLIENTKEY adds the xCLIENTKEY to the post disbursement v10 bank account validation params
func (o *PostDisbursementV10BankAccountValidationParams) SetXCLIENTKEY(xCLIENTKEY string) {
	o.XCLIENTKEY = xCLIENTKEY
}

// WithXSIGNATURE adds the xSIGNATURE to the post disbursement v10 bank account validation params
func (o *PostDisbursementV10BankAccountValidationParams) WithXSIGNATURE(xSIGNATURE string) *PostDisbursementV10BankAccountValidationParams {
	o.SetXSIGNATURE(xSIGNATURE)
	return o
}

// SetXSIGNATURE adds the xSIGNATURE to the post disbursement v10 bank account validation params
func (o *PostDisbursementV10BankAccountValidationParams) SetXSIGNATURE(xSIGNATURE string) {
	o.XSIGNATURE = xSIGNATURE
}

// WithXTIMESTAMP adds the xTIMESTAMP to the post disbursement v10 bank account validation params
func (o *PostDisbursementV10BankAccountValidationParams) WithXTIMESTAMP(xTIMESTAMP string) *PostDisbursementV10BankAccountValidationParams {
	o.SetXTIMESTAMP(xTIMESTAMP)
	return o
}

// SetXTIMESTAMP adds the xTIMESTAMP to the post disbursement v10 bank account validation params
func (o *PostDisbursementV10BankAccountValidationParams) SetXTIMESTAMP(xTIMESTAMP string) {
	o.XTIMESTAMP = xTIMESTAMP
}

// WriteToRequest writes these params to a swagger request
func (o *PostDisbursementV10BankAccountValidationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// header param X-CLIENT-KEY
	if err := r.SetHeaderParam("X-CLIENT-KEY", o.XCLIENTKEY); err != nil {
		return err
	}

	// header param X-SIGNATURE
	if err := r.SetHeaderParam("X-SIGNATURE", o.XSIGNATURE); err != nil {
		return err
	}

	// header param X-TIMESTAMP
	if err := r.SetHeaderParam("X-TIMESTAMP", o.XTIMESTAMP); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
