// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AccountInfo account info
//
// swagger:model AccountInfo
type AccountInfo struct {

	// available balance
	AvailableBalance *BalanceDetail `json:"availableBalance,omitempty"`
}

// Validate validates this account info
func (m *AccountInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAvailableBalance(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountInfo) validateAvailableBalance(formats strfmt.Registry) error {
	if swag.IsZero(m.AvailableBalance) { // not required
		return nil
	}

	if m.AvailableBalance != nil {
		if err := m.AvailableBalance.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("availableBalance")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("availableBalance")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this account info based on the context it is used
func (m *AccountInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAvailableBalance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountInfo) contextValidateAvailableBalance(ctx context.Context, formats strfmt.Registry) error {

	if m.AvailableBalance != nil {

		if swag.IsZero(m.AvailableBalance) { // not required
			return nil
		}

		if err := m.AvailableBalance.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("availableBalance")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("availableBalance")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AccountInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountInfo) UnmarshalBinary(b []byte) error {
	var res AccountInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
