// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AmountDetail amount detail
//
// swagger:model AmountDetail
type AmountDetail struct {

	// currency
	Currency string `json:"currency,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this amount detail
func (m *AmountDetail) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this amount detail based on context it is used
func (m *AmountDetail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AmountDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AmountDetail) UnmarshalBinary(b []byte) error {
	var res AmountDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
