// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Apiv1DisbursementAdditionalData apiv1 disbursement additional data
//
// swagger:model apiv1.DisbursementAdditionalData
type Apiv1DisbursementAdditionalData struct {

	// channel
	Channel string `json:"channel,omitempty"`

	// device Id
	DeviceID string `json:"deviceId,omitempty"`

	// emoney source account no
	EmoneySourceAccountNo string `json:"emoneySourceAccountNo,omitempty"`

	// platform code
	PlatformCode string `json:"platformCode,omitempty"`

	// remark
	Remark string `json:"remark,omitempty"`

	// validation reference no
	ValidationReferenceNo string `json:"validationReferenceNo,omitempty"`
}

// Validate validates this apiv1 disbursement additional data
func (m *Apiv1DisbursementAdditionalData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this apiv1 disbursement additional data based on context it is used
func (m *Apiv1DisbursementAdditionalData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Apiv1DisbursementAdditionalData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Apiv1DisbursementAdditionalData) UnmarshalBinary(b []byte) error {
	var res Apiv1DisbursementAdditionalData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
