// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Apiv1CheckVirtualAccountPaymentStatusRequest apiv1 check virtual account payment status request
//
// swagger:model apiv1.CheckVirtualAccountPaymentStatusRequest
type Apiv1CheckVirtualAccountPaymentStatusRequest struct {

	// customer no
	CustomerNo string `json:"customerNo,omitempty"`

	// inquiry request Id
	InquiryRequestID string `json:"inquiryRequestId,omitempty"`

	// partner service Id
	PartnerServiceID string `json:"partnerServiceId,omitempty"`

	// virtual account no
	VirtualAccountNo string `json:"virtualAccountNo,omitempty"`
}

// Validate validates this apiv1 check virtual account payment status request
func (m *Apiv1CheckVirtualAccountPaymentStatusRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this apiv1 check virtual account payment status request based on context it is used
func (m *Apiv1CheckVirtualAccountPaymentStatusRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Apiv1CheckVirtualAccountPaymentStatusRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Apiv1CheckVirtualAccountPaymentStatusRequest) UnmarshalBinary(b []byte) error {
	var res Apiv1CheckVirtualAccountPaymentStatusRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
