// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Apiv1URLParam apiv1 URL param
//
// swagger:model apiv1.URLParam
type Apiv1URLParam struct {

	// is deeplink
	IsDeeplink string `json:"isDeeplink,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this apiv1 URL param
func (m *Apiv1URLParam) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this apiv1 URL param based on context it is used
func (m *Apiv1URLParam) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Apiv1URLParam) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Apiv1URLParam) UnmarshalBinary(b []byte) error {
	var res Apiv1URLParam
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
