// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DisbursementAdditionalData disbursement additional data
//
// swagger:model DisbursementAdditionalData
type DisbursementAdditionalData struct {

	// channel
	Channel string `json:"channel,omitempty"`

	// device Id
	DeviceID string `json:"deviceId,omitempty"`

	// emoney source account no
	EmoneySourceAccountNo string `json:"emoneySourceAccountNo,omitempty"`

	// platform code
	PlatformCode string `json:"platformCode,omitempty"`

	// remark
	Remark string `json:"remark,omitempty"`

	// validation reference no
	ValidationReferenceNo string `json:"validationReferenceNo,omitempty"`
}

// Validate validates this disbursement additional data
func (m *DisbursementAdditionalData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this disbursement additional data based on context it is used
func (m *DisbursementAdditionalData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DisbursementAdditionalData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DisbursementAdditionalData) UnmarshalBinary(b []byte) error {
	var res DisbursementAdditionalData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
