// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InquiryBalanceResponse inquiry balance response
//
// swagger:model InquiryBalanceResponse
type InquiryBalanceResponse struct {

	// account info
	AccountInfo []*AccountInfo `json:"accountInfo"`

	// response code
	ResponseCode string `json:"responseCode,omitempty"`

	// response message
	ResponseMessage string `json:"responseMessage,omitempty"`
}

// Validate validates this inquiry balance response
func (m *InquiryBalanceResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccountInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InquiryBalanceResponse) validateAccountInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.AccountInfo) { // not required
		return nil
	}

	for i := 0; i < len(m.AccountInfo); i++ {
		if swag.IsZero(m.AccountInfo[i]) { // not required
			continue
		}

		if m.AccountInfo[i] != nil {
			if err := m.AccountInfo[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("accountInfo" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("accountInfo" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this inquiry balance response based on the context it is used
func (m *InquiryBalanceResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAccountInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InquiryBalanceResponse) contextValidateAccountInfo(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.AccountInfo); i++ {

		if m.AccountInfo[i] != nil {

			if swag.IsZero(m.AccountInfo[i]) { // not required
				return nil
			}

			if err := m.AccountInfo[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("accountInfo" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("accountInfo" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *InquiryBalanceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InquiryBalanceResponse) UnmarshalBinary(b []byte) error {
	var res InquiryBalanceResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
