// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InquiryVirtualAccountRequest inquiry virtual account request
//
// swagger:model InquiryVirtualAccountRequest
type InquiryVirtualAccountRequest struct {

	// customer no
	CustomerNo string `json:"customerNo,omitempty"`

	// partner service Id
	PartnerServiceID string `json:"partnerServiceId,omitempty"`

	// trx Id
	TrxID string `json:"trxId,omitempty"`

	// virtual account no
	VirtualAccountNo string `json:"virtualAccountNo,omitempty"`
}

// Validate validates this inquiry virtual account request
func (m *InquiryVirtualAccountRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this inquiry virtual account request based on context it is used
func (m *InquiryVirtualAccountRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InquiryVirtualAccountRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InquiryVirtualAccountRequest) UnmarshalBinary(b []byte) error {
	var res InquiryVirtualAccountRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
