// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PartnerAccessTokenRequest partner access token request
//
// swagger:model PartnerAccessTokenRequest
type PartnerAccessTokenRequest struct {

	// The OAuth2 grant type, must be "client_credentials"
	// required: true
	// example: client_credentials
	GrantType string `json:"grantType,omitempty"`
}

// Validate validates this partner access token request
func (m *PartnerAccessTokenRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this partner access token request based on context it is used
func (m *PartnerAccessTokenRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PartnerAccessTokenRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PartnerAccessTokenRequest) UnmarshalBinary(b []byte) error {
	var res PartnerAccessTokenRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
