// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PaymentGatewayNotifyAdditionalInfo payment gateway notify additional info
//
// swagger:model payment_gateway.NotifyAdditionalInfo
type PaymentGatewayNotifyAdditionalInfo struct {

	// BAG resources
	BillNumber string `json:"billNumber,omitempty"`

	// callback Url
	CallbackURL string `json:"callbackUrl,omitempty"`

	// Issuer Identifier
	IssuerID string `json:"issuerId,omitempty"`

	// Merchant identifier that is unique per each
	MerchantID string `json:"merchantId,omitempty"`

	// BSS resource
	MerchantPan string `json:"merchantPan,omitempty"`

	// Merchant user from bank
	MerchantUser string `json:"merchantUser,omitempty"`

	// .2 Amount – MDR (Merchant discount rate)alInfo string `
	NettAmount string `json:"nettAmount,omitempty"`

	// Payer name
	PayerName string `json:"payerName,omitempty"`

	// Customer Identifier can be phone number,
	PayerPhoneNumber string `json:"payerPhoneNumber,omitempty"`

	// Transaction date ISO-8601
	PaymentDate string `json:"paymentDate,omitempty"`

	// Reference number generated by Nobu
	PaymentReferenceNo string `json:"paymentReferenceNo,omitempty"`

	// Reference number generated by Issuer
	RetrievalReferenceNo string `json:"retrievalReferenceNo,omitempty"`

	// merchan (MPAN)
	SubMerchantID string `json:"subMerchantId,omitempty"`
}

// Validate validates this payment gateway notify additional info
func (m *PaymentGatewayNotifyAdditionalInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this payment gateway notify additional info based on context it is used
func (m *PaymentGatewayNotifyAdditionalInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PaymentGatewayNotifyAdditionalInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaymentGatewayNotifyAdditionalInfo) UnmarshalBinary(b []byte) error {
	var res PaymentGatewayNotifyAdditionalInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
