// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// QrisResponseScheme qris response scheme
//
// swagger:model QrisResponseScheme
type QrisResponseScheme struct {

	// additional info
	AdditionalInfo string `json:"additionalInfo,omitempty"`

	// merchant name
	MerchantName string `json:"merchantName,omitempty"`

	// partner reference no
	PartnerReferenceNo string `json:"partnerReferenceNo,omitempty"`

	// qr content
	QrContent string `json:"qrContent,omitempty"`

	// QrImage value is base64 from image QRIS. Max length is unlimited.
	QrImage string `json:"qrImage,omitempty"`

	// qr Url
	QrURL string `json:"qrUrl,omitempty"`

	// reference no
	ReferenceNo string `json:"referenceNo,omitempty"`

	// response code
	ResponseCode string `json:"responseCode,omitempty"`

	// response message
	ResponseMessage string `json:"responseMessage,omitempty"`

	// store Id
	StoreID string `json:"storeId,omitempty"`
}

// Validate validates this qris response scheme
func (m *QrisResponseScheme) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this qris response scheme based on context it is used
func (m *QrisResponseScheme) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *QrisResponseScheme) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QrisResponseScheme) UnmarshalBinary(b []byte) error {
	var res QrisResponseScheme
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
